import { NextResponse } from 'next/server';
import { ensureAuthSchema, getDatabase } from '@/db';
import { getInternalUser } from '@/app/internal-auth';
import { cloneFamily, flattenFamily, initialFamily, type FamilyDataMode, type FamilyPerson } from '@/lib/family-tree';
const TREE_ID='primary';const DATA_MODE_KEY='family_data_mode';const MAX_GENERATION=20;const MAX_MEMBERS=500;const SAMPLE_TREE_COUNTS=new Set([16,68,168]);
function isDataMode(value:unknown):value is FamilyDataMode{return value==='sample'||value==='official'||value==='empty';}
function isValidIsoDate(value:unknown):value is string{if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const[y,m,d]=value.split('-').map(Number);const date=new Date(Date.UTC(y,m-1,d));return date.getUTCFullYear()===y&&date.getUTCMonth()===m-1&&date.getUTCDate()===d;}
function isLegacySampleTree(value:FamilyPerson){return value.id===1&&value.name==='Phạm Văn An'&&SAMPLE_TREE_COUNTS.has(flattenFamily(value).length);}
function validTree(value:unknown):value is FamilyPerson{const ids=new Set<number>();let count=0;const visit=(person:unknown,g:number):boolean=>{if(!person||typeof person!=='object'||Array.isArray(person))return false;const m=person as Partial<FamilyPerson>;if(!Number.isInteger(m.id)||m.id!<1||ids.has(m.id!))return false;if(typeof m.name!=='string'||!m.name.trim()||m.name.length>100)return false;if(m.birthDate!==undefined&&!isValidIsoDate(m.birthDate))return false;if(m.deathDate!==undefined&&!isValidIsoDate(m.deathDate))return false;if(m.memorialDate!==undefined&&!isValidIsoDate(m.memorialDate))return false;if(m.generation!==g||g>MAX_GENERATION||m.children!==undefined&&!Array.isArray(m.children))return false;ids.add(m.id!);count++;if(count>MAX_MEMBERS)return false;return(m.children??[]).every(c=>visit(c,g+1));};return visit(value,1);}
function withoutPrivateIdentity(root:FamilyPerson){const publicPerson=cloneFamily(root);const visit=(p:FamilyPerson)=>{delete p.identityNumber;p.children?.forEach(visit);};visit(publicPerson);return publicPerson;}
async function getStoredDataMode():Promise<FamilyDataMode|null>{const row=await getDatabase().prepare('SELECT value FROM app_settings WHERE key=?').bind(DATA_MODE_KEY).first<{value:string}>();return isDataMode(row?.value)?row.value:null;}
export async function GET(){try{await ensureAuthSchema();const user=await getInternalUser();const[row,savedMode]=await Promise.all([getDatabase().prepare('SELECT data FROM family_tree WHERE id=?').bind(TREE_ID).first<{data:string}>(),getStoredDataMode()]);if(!row)return NextResponse.json({family:cloneFamily(initialFamily),dataMode:'sample' satisfies FamilyDataMode});if(row.data==='null')return NextResponse.json({family:null,dataMode:savedMode??'empty'});if(savedMode==='sample')return NextResponse.json({family:cloneFamily(initialFamily),dataMode:'sample' satisfies FamilyDataMode});const stored=JSON.parse(row.data) as unknown;if(!validTree(stored)||isLegacySampleTree(stored))return NextResponse.json({family:cloneFamily(initialFamily),dataMode:'sample' satisfies FamilyDataMode});return NextResponse.json({family:user?stored:withoutPrivateIdentity(stored),dataMode:savedMode??'official'});}catch{return NextResponse.json({family:cloneFamily(initialFamily),dataMode:'sample' satisfies FamilyDataMode});}}
function approvalOnly(){return NextResponse.json({message:'Dữ liệu chung không nhận ghi trực tiếp. Hãy lưu trên thiết bị và gửi yêu cầu để quản trị viên duyệt.'},{status:409});}
export async function PUT(){return approvalOnly();}
export async function DELETE(){return approvalOnly();}
