'use client';
export default function HueDesignSystem(){return <style>{`
:root{--ds-bg:#7b100b;--ds-bg2:#4b0705;--ds-surface:#5b0b08e8;--ds-surface2:#3a0605e8;--ds-surface-soft:#79140e99;--ds-gold:#e9bd57;--ds-gold-hi:#f6dc8b;--ds-text:#fff0c4;--ds-muted:#c9aa8a;--ds-border:#d5a33f66;--ds-shadow:#26010066;--ds-danger:#d55745;--ds-radius:16px;--ds-radius-lg:22px;--ds-control:44px;--ds-gap:14px;--ds-icon:20px;--ds-title:17px}
html[data-hue-mode='dark']{--ds-bg:#07111a;--ds-bg2:#03080d;--ds-surface:#0d1b27ed;--ds-surface2:#071019ed;--ds-surface-soft:#122534b8;--ds-gold:#dfb454;--ds-gold-hi:#f3d483;--ds-text:#f8e3aa;--ds-muted:#aaa393;--ds-border:#c79a4761;--ds-shadow:#0009;--ds-danger:#dc6b5e}
body,.app-shell,.content{transition:background-color .25s ease,color .25s ease,border-color .25s ease}
html[data-hue-mode='light'] .app-shell{background:linear-gradient(145deg,#5b0b08,#2d0504)!important}html[data-hue-mode='dark'] .app-shell{background:linear-gradient(145deg,#0b1924,#02070c)!important}
html[data-hue-mode='light'] .content{background-color:var(--ds-bg)!important;background-image:radial-gradient(circle at 50% 22%,#ad2a1b80,transparent 45%),linear-gradient(120deg,transparent 46%,#35060530 47%,transparent 48%)!important}html[data-hue-mode='dark'] .content{background-color:var(--ds-bg)!important;background-image:radial-gradient(circle at 50% 22%,#17334a80,transparent 45%),linear-gradient(120deg,transparent 46%,#0007 47%,transparent 48%)!important}
.topbar,.bottom-nav,.mobile-nav{border-color:var(--ds-border)!important;background:color-mix(in srgb,var(--ds-bg2) 94%,transparent)!important;color:var(--ds-text)!important}.filter-panel{border-color:var(--ds-border)!important;background:linear-gradient(180deg,color-mix(in srgb,var(--ds-bg) 90%,#000),var(--ds-bg2))!important}.content-heading{border-color:var(--ds-border)!important;background:color-mix(in srgb,var(--ds-bg2) 58%,transparent)!important}.content-heading h2,.settings-heading h2,.panel-heading strong{color:var(--ds-gold-hi)!important}.content-heading span,.settings-heading p,.setting-copy p{color:var(--ds-muted)!important}
.setting-card,.notification-settings-card,.admin-config-card,.account-manager,.audit-log-card,.secondary-view{border:1px solid var(--ds-border)!important;border-radius:var(--ds-radius)!important;background:linear-gradient(135deg,var(--ds-surface),var(--ds-surface2))!important;box-shadow:0 14px 35px var(--ds-shadow),inset 0 1px color-mix(in srgb,var(--ds-gold-hi) 12%,transparent)!important;color:var(--ds-text)!important}.setting-card{gap:14px!important}.setting-copy h3,.config-title h3,.config-title strong{font-family:inherit!important;font-size:var(--ds-title)!important;font-weight:400!important;line-height:1.25!important;color:var(--ds-gold-hi)!important}.setting-icon{width:22px!important;height:22px!important;min-width:22px!important;padding:0!important;border:0!important;border-radius:0!important;background:transparent!important;box-shadow:none!important;color:var(--ds-gold)!important}.setting-icon svg{width:var(--ds-icon)!important;height:var(--ds-icon)!important;stroke-width:1.8!important}
button,.button,input,select,textarea{transition:border-color .18s ease,background .18s ease,color .18s ease,transform .12s ease,box-shadow .18s ease}input,select,textarea{border:1px solid var(--ds-border)!important;border-radius:12px!important;background:color-mix(in srgb,var(--ds-bg2) 74%,transparent)!important;color:var(--ds-text)!important;outline:none}input:focus,select:focus,textarea:focus{border-color:var(--ds-gold)!important;box-shadow:0 0 0 3px color-mix(in srgb,var(--ds-gold) 16%,transparent)!important}button:active{transform:scale(.985)}
.data-actions button,.settings-view button:not(.settings-collapse-header),.secondary-view button{min-height:var(--ds-control);border:1px solid var(--ds-border)!important;border-radius:12px!important;background:linear-gradient(180deg,color-mix(in srgb,var(--ds-bg) 90%,#c4422b),var(--ds-bg2))!important;color:var(--ds-gold-hi)!important}.danger-action{color:#ffd1c8!important;border-color:color-mix(in srgb,var(--ds-danger) 58%,transparent)!important}
.search-box,.view-chip,.zoom-controls{border-color:var(--ds-border)!important;background:color-mix(in srgb,var(--ds-bg2) 76%,transparent)!important;color:var(--ds-text)!important}.generation-list button{color:var(--ds-muted)!important}.generation-list button.selected{border-color:var(--ds-gold)!important;background:color-mix(in srgb,var(--ds-bg) 70%,transparent)!important;color:var(--ds-gold-hi)!important;box-shadow:inset 3px 0 var(--ds-gold)!important}
.person-card{border-color:var(--ds-gold)!important;background:linear-gradient(140deg,#fff6dc,#e4c36f)!important}.root-card{background:linear-gradient(135deg,#f6d87e,#dca22e)!important}html[data-hue-mode='dark'] .person-card{background:linear-gradient(140deg,#182b37,#0c1720)!important;color:#f2d688!important;box-shadow:0 7px 20px #0008,inset 0 0 0 3px #09131b,inset 0 0 0 4px #a77a2d!important}html[data-hue-mode='dark'] .person-copy small{color:#a9a18e!important}html[data-hue-mode='dark'] .avatar-mark{background:#08131c!important}
.system-push-confirm{border-color:var(--ds-border)!important;background:linear-gradient(145deg,color-mix(in srgb,var(--ds-surface) 96%,transparent),color-mix(in srgb,var(--ds-surface2) 96%,transparent))!important;color:var(--ds-text)!important}.system-push-actions .system-push-primary{background:var(--ds-gold-hi)!important;color:var(--ds-bg2)!important}
.settings-collapse-header:after{display:flex!important;align-items:center!important;justify-content:center!important;border-color:var(--ds-gold)!important;background:color-mix(in srgb,var(--ds-bg2) 80%,transparent)!important;color:var(--ds-gold-hi)!important}.settings-collapse-card.is-settings-collapsed{border-color:var(--ds-border)!important;background:linear-gradient(120deg,var(--ds-surface),var(--ds-surface2))!important;box-shadow:0 14px 35px var(--ds-shadow)!important}
.tabs button,.bottom-nav button{color:var(--ds-muted)!important}.tabs button.active,.bottom-nav button.active{color:var(--ds-gold-hi)!important}.tabs button.active:after{background:var(--ds-gold-hi)!important}
*{scrollbar-color:color-mix(in srgb,var(--ds-gold) 68%,transparent) color-mix(in srgb,var(--ds-bg2) 75%,transparent)}
@media(max-width:740px){:root{--ds-radius:16px;--ds-control:42px;--ds-gap:12px}.settings-view{width:calc(100% - 28px)!important}.setting-card{padding-left:18px!important;padding-right:18px!important}.settings-collapse-card.is-settings-collapsed{height:64px!important;min-height:64px!important;max-height:64px!important}}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{scroll-behavior:auto!important;transition:none!important;animation-duration:.001ms!important;animation-iteration-count:1!important}}
`}</style>}
