'use client';
import { useEffect,useRef,useState } from 'react';
import { Check,DatabaseBackup,Download,Send,ShieldCheck,Trash2,Upload,X } from 'lucide-react';
import { clearLocalWorkspace,emptyLocalWorkspace,LOCAL_BACKUP_SCOPE,LOCAL_WORKSPACE_EVENT,markChangesSubmitted,readLocalWorkspace,writeLocalWorkspace,type LocalChange,type LocalWorkspace } from '@/lib/local-data-workspace';

type RequestRow={id:string;requester_username:string;summary:string;payload:string;status:string;created_at:number};
const labels:Record<string,string>={family:'Gia phả / thành viên',event:'Sự kiện',material:'Tư liệu',media:'Media'};

export default function LocalDataManagement({isAdmin=false}:{isAdmin?:boolean}){
 const[workspace,setWorkspace]=useState<LocalWorkspace>(emptyLocalWorkspace());
 const[requests,setRequests]=useState<RequestRow[]>([]); const[message,setMessage]=useState(''); const fileRef=useRef<HTMLInputElement>(null);
 const refresh=()=>setWorkspace(readLocalWorkspace());
 const load=async()=>{const r=await fetch('/api/shared-change-requests',{cache:'no-store'});if(r.ok){const d=await r.json() as {requests?:RequestRow[]};setRequests(d.requests||[]);}};
 useEffect(()=>{refresh();void load();window.addEventListener(LOCAL_WORKSPACE_EVENT,refresh);return()=>window.removeEventListener(LOCAL_WORKSPACE_EVENT,refresh);},[]);
 const summary=workspace.pendingChanges.length?workspace.pendingChanges.map(c=>labels[c.kind]||c.kind).reduce<Record<string,number>>((a,k)=>(a[k]=(a[k]||0)+1,a),{}):{};
 const summaryText=Object.entries(summary).map(([k,v])=>`${v} ${k}`).join(' · ')||'Không có thay đổi đang chờ';
 const backup=()=>{const blob=new Blob([JSON.stringify({scope:LOCAL_BACKUP_SCOPE,exportedAt:new Date().toISOString(),workspace},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`giapha-local-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Đã sao lưu dữ liệu local của thiết bị này.');};
 const restore=async(file?:File)=>{if(!file)return;try{const d=JSON.parse(await file.text()) as {scope?:string;workspace?:LocalWorkspace};if(d.scope!==LOCAL_BACKUP_SCOPE||d.workspace?.version!==1)throw new Error();writeLocalWorkspace(d.workspace);setMessage('Đã phục hồi local. Dữ liệu chung không thay đổi.');}catch{setMessage('Tệp sao lưu local không hợp lệ.');}if(fileRef.current)fileRef.current.value='';};
 const submit=async()=>{const changes=workspace.pendingChanges;if(!changes.length)return;const r=await fetch('/api/shared-change-requests',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({changes,deviceLabel:navigator.userAgent.slice(0,120)})});const d=await r.json() as {id?:string;message?:string};if(r.ok&&d.id){markChangesSubmitted(changes.map(c=>c.id),d.id);setMessage('Đã gửi quản trị viên duyệt. Dữ liệu chung chưa thay đổi.');void load();}else setMessage(d.message||'Không gửi được yêu cầu.');};
 const review=async(id:string,decision:'approved'|'rejected')=>{const r=await fetch('/api/shared-change-requests',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,decision})});const d=await r.json() as {message?:string};setMessage(r.ok?(decision==='approved'?'Đã duyệt và áp dụng dữ liệu chung.':'Đã từ chối yêu cầu.'):d.message||'Không xử lý được yêu cầu.');void load();};
 const details=(row:RequestRow):LocalChange[]=>{try{return JSON.parse(row.payload) as LocalChange[];}catch{return[];}};
 return <section className="local-data-center">
  <article className="setting-card"><div className="setting-icon"><DatabaseBackup/></div><div className="setting-copy"><h3>Dữ liệu trên thiết bị này</h3><p>Sao lưu, phục hồi và xóa chỉ tác động dữ liệu local của máy hiện tại. Không ảnh hưởng dữ liệu chung.</p></div><div className="data-actions"><button onClick={backup}><Download/>Sao lưu local</button><button onClick={()=>fileRef.current?.click()}><Upload/>Phục hồi local</button><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={e=>void restore(e.target.files?.[0])}/><button className="danger-action" onClick={()=>{if(confirm('Xóa dữ liệu local trên thiết bị này?')){clearLocalWorkspace();setMessage('Đã xóa dữ liệu local. Dữ liệu chung được giữ nguyên.');}}}><Trash2/>Xóa local</button></div></article>
  <article className="setting-card shared-submit-card"><div className="setting-icon"><Send/></div><div className="setting-copy"><h3>Đẩy lên dữ liệu chung</h3><p>Mọi thay đổi được giữ trên máy. Chỉ sau khi gửi và được quản trị viên duyệt mới cập nhật dữ liệu chung.</p><div className="setting-meta"><ShieldCheck/><span>{summaryText}</span></div>{workspace.pendingChanges.length>0?<div className="pending-detail">{workspace.pendingChanges.map(c=><small key={c.id}>{labels[c.kind]||c.kind} · {c.action==='create'?'Thêm':c.action==='delete'?'Xóa':'Sửa'} · {c.label}</small>)}</div>:null}</div><div className="data-actions"><button disabled={!workspace.pendingChanges.length} onClick={()=>void submit()}><Send/>Gửi quản trị viên duyệt</button></div></article>
  {requests.length>0?<article className="setting-card approval-list"><div className="setting-copy"><h3>{isAdmin?'Yêu cầu dữ liệu chung':'Yêu cầu đã gửi'}</h3><p>{isAdmin?'Kiểm tra chi tiết trước khi duyệt.':'Theo dõi trạng thái dữ liệu đã gửi.'}</p>{requests.map(r=><div className="approval-row" key={r.id}><div><strong>{r.summary}</strong><small>{r.requester_username} · {new Date(r.created_at).toLocaleString('vi-VN')} · {r.status==='pending'?'Chờ duyệt':r.status==='approved'?'Đã duyệt':'Từ chối'}</small><details><summary>Xem dữ liệu đề nghị</summary>{details(r).map(c=><p key={c.id}><b>{labels[c.kind]||c.kind}</b> · {c.action} · {c.label}</p>)}</details></div>{isAdmin&&r.status==='pending'?<span><button onClick={()=>void review(r.id,'approved')}><Check/>Duyệt</button><button className="danger-action" onClick={()=>void review(r.id,'rejected')}><X/>Từ chối</button></span>:null}</div>)}</div></article>:null}
  {message?<output className="admin-message"><ShieldCheck/>{message}</output>:null}
  <style>{`.local-data-center{display:grid;gap:12px}.pending-detail{display:grid;gap:4px;margin-top:9px}.approval-row{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;padding:12px 0;border-top:1px solid color-mix(in srgb,currentColor 14%,transparent)}.approval-row>div{display:grid;gap:4px;min-width:0}.approval-row small{opacity:.68}.approval-row>span{display:flex;gap:8px}.approval-row button{display:inline-flex;align-items:center;gap:5px}.approval-row svg{width:15px;height:15px}.approval-row details{margin-top:5px}.approval-row details p{margin:5px 0;font-size:11px}`}</style>
 </section>;
}
