'use client';
import { useEffect,useRef,useState } from 'react';
import { createPortal } from 'react-dom';
import { BellRing,Check,DatabaseBackup,Download,Mail,Save,Send,ShieldCheck,Trash2,Upload,X } from 'lucide-react';
import { clearLocalWorkspace,emptyLocalWorkspace,LOCAL_BACKUP_SCOPE,LOCAL_WORKSPACE_EVENT,markChangesSubmitted,readLocalWorkspace,writeLocalWorkspace,type LocalChange,type LocalWorkspace } from '@/lib/local-data-workspace';

type RequestRow={id:string;requester_username:string;summary:string;payload:string;status:string;created_at:number};
const labels:Record<string,string>={family:'Gia phả / thành viên',event:'Sự kiện',material:'Tư liệu',media:'Hình ảnh / media'};
const pretty=(value:unknown)=>JSON.stringify(value,null,2);

export default function LocalDataManagement({isAdmin=false}:{isAdmin?:boolean}){
 const[workspace,setWorkspace]=useState<LocalWorkspace>(emptyLocalWorkspace());const[requests,setRequests]=useState<RequestRow[]>([]);const[message,setMessage]=useState('');const[target,setTarget]=useState<HTMLElement|null>(null);const[email,setEmail]=useState('');const[emailProvider,setEmailProvider]=useState(false);const fileRef=useRef<HTMLInputElement>(null);
 const refresh=()=>setWorkspace(readLocalWorkspace());
 const load=async()=>{const r=await fetch('/api/shared-change-requests',{cache:'no-store'});if(r.ok){const d=await r.json() as {requests?:RequestRow[]};setRequests(d.requests||[]);}};
 const loadNoticeSettings=async()=>{if(!isAdmin)return;const r=await fetch('/api/admin/change-notifications',{cache:'no-store'});if(!r.ok)return;const d=await r.json() as {email?:string;emailProviderConfigured?:boolean};setEmail(d.email||'');setEmailProvider(Boolean(d.emailProviderConfigured));};
 useEffect(()=>{refresh();void load();void loadNoticeSettings();window.addEventListener(LOCAL_WORKSPACE_EVENT,refresh);return()=>window.removeEventListener(LOCAL_WORKSPACE_EVENT,refresh);},[]);
 useEffect(()=>{let anchor:HTMLElement|null=null;const mount=()=>{const legacy=document.querySelector<HTMLElement>('.setting-card.data-management');if(!legacy){setTarget(null);return;}if(anchor?.isConnected){setTarget(anchor);return;}anchor=document.createElement('div');anchor.className='local-data-management-mount';legacy.parentElement?.insertBefore(anchor,legacy);legacy.dataset.localFirst='true';setTarget(anchor);};mount();const observer=new MutationObserver(mount);observer.observe(document.body,{childList:true,subtree:true});return()=>{observer.disconnect();anchor?.remove();};},[]);
 const summary=workspace.pendingChanges.length?workspace.pendingChanges.map(c=>labels[c.kind]||c.kind).reduce<Record<string,number>>((a,k)=>(a[k]=(a[k]||0)+1,a),{}):{};const summaryText=Object.entries(summary).map(([k,v])=>`${v} ${k}`).join(' · ')||'Không có thay đổi local đang chờ gửi';
 const backup=()=>{const blob=new Blob([JSON.stringify({scope:LOCAL_BACKUP_SCOPE,exportedAt:new Date().toISOString(),workspace},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`giapha-local-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Đã sao lưu dữ liệu local của thiết bị này. Dữ liệu chung không bị tác động.');};
 const restore=async(file?:File)=>{if(!file)return;try{const d=JSON.parse(await file.text()) as {scope?:string;workspace?:LocalWorkspace};if(d.scope!==LOCAL_BACKUP_SCOPE||d.workspace?.version!==1)throw new Error();writeLocalWorkspace(d.workspace);setMessage('Đã phục hồi dữ liệu local trên thiết bị này. Dữ liệu chung không thay đổi.');}catch{setMessage('Tệp sao lưu local không hợp lệ.');}if(fileRef.current)fileRef.current.value='';};
 const submit=async()=>{const changes=workspace.pendingChanges;if(!changes.length)return;const r=await fetch('/api/shared-change-requests',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({changes,deviceLabel:navigator.userAgent.slice(0,120)})});const d=await r.json() as {id?:string;message?:string;notified?:{accounts?:number;email?:{sent?:boolean;reason?:string}}};if(r.ok&&d.id){markChangesSubmitted(changes.map(c=>c.id),d.id);const emailState=d.notified?.email?.sent?'Email đã gửi':'Email đang chờ cấu hình/kết nối';setMessage(`Đã gửi quản trị viên duyệt. ${d.notified?.accounts||0} tài khoản quản trị đã nhận thông báo · ${emailState}. Dữ liệu chung chưa thay đổi.`);void load();}else setMessage(d.message||'Không gửi được yêu cầu.');};
 const review=async(id:string,decision:'approved'|'rejected')=>{const r=await fetch('/api/shared-change-requests',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,decision})});const d=await r.json() as {message?:string};setMessage(r.ok?(decision==='approved'?'Đã duyệt và áp dụng dữ liệu vào dữ liệu chung.':'Đã từ chối yêu cầu; dữ liệu chung không thay đổi.'):d.message||'Không xử lý được yêu cầu.');void load();};
 const saveEmail=async()=>{const r=await fetch('/api/admin/change-notifications',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({email})});const d=await r.json() as {message?:string};setMessage(r.ok?'Đã lưu email nhận yêu cầu duyệt.':d.message||'Không lưu được email.');};
 const enableDeviceNotice=async()=>{if(typeof Notification==='undefined'){setMessage('Thiết bị/trình duyệt này không hỗ trợ thông báo hệ thống.');return;}const permission=await Notification.requestPermission();setMessage(permission==='granted'?'Đã bật thông báo trên thiết bị cho tài khoản này.':'Chưa cấp quyền thông báo trên thiết bị.');};
 const details=(row:RequestRow):LocalChange[]=>{try{return JSON.parse(row.payload) as LocalChange[];}catch{return[];}};
 const panel=<section className="local-data-center" aria-label="Quản lý dữ liệu local và dữ liệu chung">
  <article className="setting-card local-device-card"><div className="setting-icon"><DatabaseBackup/></div><div className="setting-copy"><h3>Dữ liệu trên thiết bị này</h3><p>Sao lưu, phục hồi và xóa chỉ áp dụng trên thiết bị hiện tại. Ba thao tác này tuyệt đối không xóa, ghi đè hoặc phục hồi dữ liệu chung.</p><div className="setting-meta"><ShieldCheck/><span>Phạm vi: thiết bị này · Local only</span></div></div><div className="data-actions local-device-actions"><button onClick={backup}><Download/>Sao lưu</button><button onClick={()=>fileRef.current?.click()}><Upload/>Phục hồi</button><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={e=>void restore(e.target.files?.[0])}/><button className="danger-action" onClick={()=>{if(confirm('Xóa dữ liệu local trên thiết bị này? Dữ liệu chung vẫn được giữ nguyên.')){clearLocalWorkspace();setMessage('Đã xóa dữ liệu local. Dữ liệu chung được giữ nguyên.');}}}><Trash2/>Xóa</button></div></article>
  <article className="setting-card shared-submit-card"><div className="setting-icon"><Send/></div><div className="setting-copy"><h3>Đẩy lên dữ liệu chung</h3><p>Thành viên, gia phả, sự kiện và tư liệu được lưu local trước. Nút này chỉ gửi yêu cầu cho quản trị viên, chưa ghi vào dữ liệu chung.</p><div className="setting-meta"><ShieldCheck/><span>{summaryText}</span></div>{workspace.pendingChanges.length>0?<div className="pending-detail">{workspace.pendingChanges.map(c=><small key={c.id}><b>{labels[c.kind]||c.kind}</b> · {c.action==='create'?'Thêm':c.action==='delete'?'Xóa':'Sửa'} · {c.label}</small>)}</div>:null}<div className="approval-route"><span><BellRing/>Thông báo tài khoản quản trị</span><span><Mail/>Email quản trị</span><span><ShieldCheck/>Chỉ ghi dữ liệu sau khi được duyệt</span></div></div><div className="data-actions"><button disabled={!workspace.pendingChanges.length} onClick={()=>void submit()}><Send/>Gửi quản trị viên duyệt</button></div></article>
  {isAdmin?<article className="setting-card notification-config"><div className="setting-icon"><BellRing/></div><div className="setting-copy"><h3>Thông báo phê duyệt</h3><p>Yêu cầu mới luôn tạo thông báo trong tài khoản quản trị. Có thể bật thêm thông báo hệ thống trên thiết bị và email.</p><label className="approval-email"><span>Email nhận yêu cầu</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@example.com"/></label><small className={emailProvider?'provider-ok':'provider-warn'}>{emailProvider?'Dịch vụ gửi email đã kết nối.':'Chưa có RESEND_API_KEY trên Cloudflare; email sẽ bắt đầu gửi ngay khi secret này được cấu hình.'}</small></div><div className="data-actions"><button onClick={()=>void saveEmail()}><Save/>Lưu email</button><button onClick={()=>void enableDeviceNotice()}><BellRing/>Bật thông báo thiết bị</button></div></article>:null}
  {requests.length>0?<article className="setting-card approval-list"><div className="setting-icon"><BellRing/></div><div className="setting-copy"><h3>{isAdmin?'Yêu cầu cập nhật dữ liệu chung':'Yêu cầu đã gửi'}</h3><p>{isAdmin?'Kiểm tra từng nội dung và dữ liệu trước/sau. Dữ liệu chỉ được áp dụng sau khi nhấn Duyệt.':'Theo dõi trạng thái các thay đổi đã gửi quản trị viên.'}</p>{requests.map(r=><div className={`approval-row status-${r.status}`} key={r.id}><div><strong>{r.summary}</strong><small>{r.requester_username} · {new Date(r.created_at).toLocaleString('vi-VN')} · {r.status==='pending'?'Chờ duyệt':r.status==='approved'?'Đã duyệt':'Từ chối'}</small><details><summary>Xem đầy đủ dữ liệu đề nghị</summary>{details(r).map(c=><section className="change-full" key={c.id}><p><b>{labels[c.kind]||c.kind}</b> · {c.action==='create'?'Thêm':c.action==='delete'?'Xóa':'Sửa'} · {c.label}</p>{isAdmin?<details><summary>Dữ liệu trước / sau</summary><pre>{pretty({before:c.before??null,after:c.after??null})}</pre></details>:null}</section>)}</details></div>{isAdmin&&r.status==='pending'?<span><button onClick={()=>void review(r.id,'approved')}><Check/>Duyệt</button><button className="danger-action" onClick={()=>void review(r.id,'rejected')}><X/>Từ chối</button></span>:null}</div>)}</div></article>:null}
  {message?<output className="admin-message"><ShieldCheck/>{message}</output>:null}
  <style>{`.setting-card.data-management[data-local-first="true"]>.setting-icon,.setting-card.data-management[data-local-first="true"]>.setting-copy,.setting-card.data-management[data-local-first="true"]>.data-actions{display:none!important}.local-data-management-mount{display:block;width:100%}.local-data-center{display:grid;gap:12px;width:100%;margin-bottom:12px}.local-data-center .setting-card{width:100%}.local-device-actions{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:8px!important;width:100%!important}.local-device-actions button{min-width:0!important;width:100%!important;justify-content:center!important;padding-left:8px!important;padding-right:8px!important;white-space:nowrap!important}.local-device-actions button svg{flex:0 0 auto}.pending-detail{display:grid;gap:6px;margin-top:10px;padding:10px 12px;border-radius:14px;background:color-mix(in srgb,currentColor 5%,transparent)}.pending-detail small{line-height:1.45}.approval-route{display:flex;flex-wrap:wrap;gap:7px;margin-top:11px}.approval-route span{display:inline-flex;align-items:center;gap:5px;font-size:11px;opacity:.78}.approval-route svg{width:14px;height:14px}.approval-email{display:grid;gap:6px;margin-top:12px}.approval-email input{width:100%;min-height:42px;border-radius:12px;padding:0 12px}.provider-ok,.provider-warn{display:block;margin-top:7px;line-height:1.4;opacity:.7}.provider-warn{opacity:.82}.approval-row{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;padding:13px 0;border-top:1px solid color-mix(in srgb,currentColor 14%,transparent)}.approval-row>div{display:grid;gap:5px;min-width:0}.approval-row small{opacity:.68}.approval-row>span{display:flex;gap:8px;flex-wrap:wrap}.approval-row button{display:inline-flex;align-items:center;gap:5px}.approval-row svg{width:15px;height:15px}.approval-row details{margin-top:5px}.change-full{padding:7px 0;border-top:1px dashed color-mix(in srgb,currentColor 12%,transparent)}.change-full p{margin:4px 0;font-size:11px;line-height:1.45}.change-full pre{max-height:240px;overflow:auto;white-space:pre-wrap;word-break:break-word;font-size:9px;line-height:1.35;padding:9px;border-radius:10px;background:rgba(0,0,0,.18)}@media(max-width:640px){.local-device-actions{grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:6px!important}.local-device-actions button{font-size:12px!important;padding:0 5px!important}.local-device-actions button svg{width:15px!important;height:15px!important}.approval-row{display:grid}.approval-row>span{width:100%}.approval-row>span button{flex:1;justify-content:center}}`}</style>
 </section>;
 return target?createPortal(panel,target):null;
}
