'use client';
import { useEffect } from 'react';
import { queueLocalChange,readLocalWorkspace,writeLocalWorkspace } from '@/lib/local-data-workspace';

type EventRow=Record<string,unknown>&{id:string};type MaterialRow=Record<string,unknown>&{id:string;title?:string};
function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});}
export default function LocalDomainWriteGuard(){useEffect(()=>{const nativeFetch=window.fetch.bind(window);window.fetch=(async(input:RequestInfo|URL,init?:RequestInit)=>{const url=typeof input==='string'?input:input instanceof URL?input.toString():input.url;const method=(init?.method||(typeof input!=='string'&&!(input instanceof URL)?input.method:'GET')).toUpperCase();let workspace=readLocalWorkspace();const eventKind=url.includes('/api/events/family')?'family':url.includes('/api/events/chapa')?'tomb':null;
 if(eventKind&&method==='GET'){const response=await nativeFetch(input,init);if(!response.ok)return response;const shared=await response.clone().json() as {events?:EventRow[];canEdit?:boolean;sampleMode?:boolean};const local=workspace.events?.[eventKind];if(Array.isArray(local))return json({...shared,events:local,localOnly:true});if(Array.isArray(shared.events)){writeLocalWorkspace({...workspace,events:{...(workspace.events||{}),[eventKind]:shared.events}});return json({...shared,localOnly:false});}return response;}
 if(eventKind&&['POST','PUT','DELETE'].includes(method)){let body:Record<string,unknown>={};try{body=JSON.parse(String(init?.body||'{}'));}catch{}workspace=readLocalWorkspace();const existing=Array.isArray(workspace.events?.[eventKind])?workspace.events![eventKind] as EventRow[]:[];const id=typeof body.id==='string'?body.id:crypto.randomUUID();const current=existing.find(e=>e.id===id);const now=Date.now();if(method==='DELETE'){const next=existing.filter(e=>e.id!==id);queueLocalChange({kind:'event',action:'delete',label:String(current?.title||current?.location||`${eventKind==='family'?'Việc họ':'Chạp mộ'} ${id}`),before:{eventKind,event:current}}, {events:{...(workspace.events||{}),[eventKind]:next}});return json({ok:true,localOnly:true});}const event={...(current||{}),...body,id,createdAt:typeof current?.createdAt==='number'?current.createdAt:now,updatedAt:now,createdBy:typeof current?.createdBy==='string'?current.createdBy:'local'} as EventRow;const next=current?existing.map(e=>e.id===id?event:e):[...existing,event];queueLocalChange({kind:'event',action:current?'update':'create',label:String(event.title||event.location||id),before:current?{eventKind,event:current}:undefined,after:{eventKind,event}}, {events:{...(workspace.events||{}),[eventKind]:next}});return json({ok:true,event,localOnly:true});}
 if(url.endsWith('/api/materials')&&method==='GET'){const response=await nativeFetch(input,init);if(!response.ok)return response;const shared=await response.clone().json() as {items?:MaterialRow[];sampleMode?:boolean};workspace=readLocalWorkspace();if(Array.isArray(workspace.materials))return json({...shared,items:workspace.materials,localOnly:true});if(Array.isArray(shared.items)){writeLocalWorkspace({...workspace,materials:shared.items});return json({...shared,localOnly:false});}return response;}
 if(url.endsWith('/api/materials')&&['POST','PATCH','DELETE'].includes(method)){let body:Record<string,unknown>={};try{body=JSON.parse(String(init?.body||'{}'));}catch{}workspace=readLocalWorkspace();const existing=Array.isArray(workspace.materials)?workspace.materials as MaterialRow[]:[];const id=typeof body.id==='string'?body.id:crypto.randomUUID();const current=existing.find(i=>i.id===id);if(method==='DELETE'){const next=existing.filter(i=>i.id!==id);queueLocalChange({kind:'material',action:'delete',label:String(current?.title||id),before:{item:current}}, {materials:next});return json({ok:true,deletedIds:[id],localOnly:true});}const now=Date.now();const item={...(current||{}),id,parent_id:body.parentId??current?.parent_id??null,kind:body.kind??current?.kind??'note',title:String(body.title??current?.title??''),content:String(body.content??current?.content??''),created_by_username:String(current?.created_by_username||'local'),updated_by_username:'local',created_at:typeof current?.created_at==='number'?current.created_at:now,updated_at:now} as MaterialRow;const next=current?existing.map(i=>i.id===id?item:i):[...existing,item];queueLocalChange({kind:'material',action:current?'update':'create',label:String(item.title||id),before:current?{item:current}:undefined,after:{item}}, {materials:next});return json({item,localOnly:true});}
 return nativeFetch(input,init);}) as typeof window.fetch;return()=>{window.fetch=nativeFetch;};},[]);return null;}
