'use client';

export default function OverviewPremiumRedesign(){
 return <style>{`
  :root{--hue-bg:#7d100b;--hue-bg-deep:#4a0705;--hue-panel:#650d09e8;--hue-panel-2:#3d0605f2;--hue-gold:#f1cc68;--hue-gold-soft:#d9ae4e;--hue-text:#f8df9a;--hue-muted:#c9aa88;--hue-shadow:#22000070;--hue-line:#e0b34b70}
  html[data-hue-mode='dark']{--hue-bg:#07111a;--hue-bg-deep:#03080d;--hue-panel:#0b1722ed;--hue-panel-2:#050d15f5;--hue-gold:#efc765;--hue-gold-soft:#c99b47;--hue-text:#f5d88d;--hue-muted:#a9a18f;--hue-shadow:#0000009a;--hue-line:#d4a84f69}
  html[data-hue-mode='light'] body{background:radial-gradient(circle at 50% 18%,#b22a1b 0,#7d100b 34%,#4a0705 100%)!important}
  html[data-hue-mode='dark'] body{background:radial-gradient(circle at 50% 18%,#152b3d 0,#08131d 35%,#03080d 100%)!important}
  html[data-hue-mode='dark'] .app-shell,html[data-hue-mode='dark'] .app-main,html[data-hue-mode='dark'] .main-content{background-color:transparent!important}
  html[data-hue-mode='dark'] .topbar,html[data-hue-mode='dark'] .bottom-nav{background:linear-gradient(180deg,#07131dec,#03080df5)!important;border-color:#c99b4759!important;box-shadow:0 -10px 35px #0007!important}
  html[data-hue-mode='dark'] .setting-card,html[data-hue-mode='dark'] .notification-settings-card,html[data-hue-mode='dark'] .admin-config-card,html[data-hue-mode='dark'] .account-manager,html[data-hue-mode='dark'] .audit-log-card{background:linear-gradient(145deg,#101d29ed,#07111aed)!important;border-color:#c99b474f!important;color:var(--hue-text)!important;box-shadow:0 14px 35px #0006,inset 0 1px #f6d47b13!important}
  html[data-hue-mode='dark'] input,html[data-hue-mode='dark'] select,html[data-hue-mode='dark'] textarea{background:#061019e8!important;border-color:#bd934642!important;color:#f0d58e!important}
  .overview-view{position:relative;isolation:isolate;width:min(760px,calc(100% - 34px))!important;margin:auto!important;padding:42px 30px 30px!important;overflow:hidden;text-align:center;border:1px solid var(--hue-line)!important;border-radius:24px!important;background:linear-gradient(145deg,var(--hue-panel) 0%,var(--hue-panel-2) 72%,var(--hue-bg-deep) 100%)!important;box-shadow:0 24px 65px var(--hue-shadow),inset 0 1px #ffe8a124!important;backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px)}
  .overview-view:before{content:'';position:absolute;z-index:-2;left:50%;top:51%;width:min(570px,92vw);aspect-ratio:1;transform:translate(-50%,-50%);border-radius:50%;opacity:.38;background:repeating-radial-gradient(circle at center,transparent 0 28px,#e8bc531b 29px 30px,transparent 31px 43px),conic-gradient(from 0deg,#e8bc5311 0 8deg,transparent 8deg 22deg,#e8bc5311 22deg 30deg,transparent 30deg 45deg);box-shadow:inset 0 0 0 1px #e8bc532b,inset 0 0 0 18px #e8bc5308,inset 0 0 0 20px #e8bc5320;pointer-events:none}
  .overview-view:after{content:'TỔNG QUAN DÒNG HỌ';position:absolute;top:15px;left:50%;transform:translateX(-50%);white-space:nowrap;padding:5px 18px;border:1px solid #d9aa4859;border-radius:999px;background:linear-gradient(180deg,var(--hue-bg),var(--hue-bg-deep));color:var(--hue-gold);font-family:var(--font-serif);font-size:13px;font-weight:600;letter-spacing:.08em;box-shadow:0 5px 20px #1800004a,inset 0 1px #ffe69c30}
  .overview-stats{position:relative;display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:12px!important;margin:0!important;padding-top:26px}
  .overview-stats:before{content:'';position:absolute;top:3px;left:7%;right:7%;height:1px;background:linear-gradient(90deg,transparent,var(--hue-gold-soft),transparent);opacity:.7}
  .overview-stats>div{position:relative;min-height:128px;display:flex!important;flex-direction:column;align-items:center;justify-content:center;gap:8px!important;padding:17px 8px!important;overflow:hidden;border:1px solid #d5a13e69!important;border-radius:18px!important;background:linear-gradient(155deg,color-mix(in srgb,var(--hue-bg) 72%,transparent),color-mix(in srgb,var(--hue-bg-deep) 88%,transparent))!important;box-shadow:inset 0 1px #ffe49a20,0 12px 27px var(--hue-shadow)!important}
  .overview-stats>div:before{content:'✦';position:absolute;top:8px;color:#e7bd5d8c;font-size:9px}.overview-stats>div:after{content:'';position:absolute;inset:5px;border:1px solid #d6a54820;border-radius:14px;pointer-events:none}
  .overview-stats strong{display:block;color:var(--hue-text)!important;font-family:var(--font-serif)!important;font-size:31px!important;font-weight:600!important;line-height:1.05;text-shadow:0 2px 14px #e5ad3d24}.overview-stats>div:nth-child(3) strong{max-width:110px;font-size:22px!important;line-height:1.05;letter-spacing:.05em}.overview-stats span{color:var(--hue-muted)!important;font-size:10px!important;letter-spacing:.05em}
  .overview-view>button{position:relative;width:min(430px,100%);height:62px;margin-top:25px!important;padding:0 52px 0 74px!important;border:1px solid var(--hue-gold)!important;border-radius:22px!important;background:linear-gradient(180deg,#a92b1d,#72100b)!important;box-shadow:0 12px 30px var(--hue-shadow),inset 0 1px #ffd87970,0 0 0 4px #dcae4110!important;color:#ffe09a!important;font-family:var(--font-serif);font-size:18px!important;font-weight:500!important;letter-spacing:.02em;transition:transform .18s ease,box-shadow .18s ease}
  html[data-hue-mode='dark'] .overview-view>button{background:linear-gradient(180deg,#173047,#08131f)!important}
  .overview-view>button:before{content:'♜';position:absolute;left:28px;top:50%;transform:translateY(-50%);color:#efc967;font-size:25px}.overview-view>button:after{content:'›';position:absolute;right:25px;top:50%;transform:translateY(-52%);font-family:Arial,sans-serif;font-size:30px;font-weight:300;color:#f5d579}.overview-view>button:active{transform:scale(.985)}
  html[data-hue-mode='dark'] .sample-data-banner,html[data-hue-mode='dark'] .sample-notice,html[data-hue-mode='dark'] .sample-data-notice{background:linear-gradient(145deg,#0d1c28,#071019)!important;border-color:#d0a24b69!important;color:#e7c877!important}
  @media(max-width:580px){.overview-view{width:calc(100% - 28px)!important;padding:39px 17px 23px!important;border-radius:21px!important}.overview-view:after{top:13px;font-size:11px;padding:4px 14px}.overview-stats{gap:8px!important;padding-top:24px}.overview-stats>div{min-height:112px;padding:14px 5px!important;border-radius:15px!important}.overview-stats strong{font-size:25px!important}.overview-stats>div:nth-child(3) strong{font-size:18px!important}.overview-stats span{font-size:9px!important}.overview-view>button{height:56px;margin-top:18px!important;font-size:17px!important}.overview-view>button:before{left:22px;font-size:22px}.overview-view>button:after{right:20px}.overview-view:before{width:115vw}}
 `}</style>;
}
