'use client';

import { DAY_HERO_DATA, NIGHT_HERO_DATA } from './overview-hero-data.generated';

export default function OverviewV5Tune() {
  return <style>{`
/* V11: final reference-match layer. All hero artwork is in-bundle; no runtime image request. */
html{--pg4-hero-day:url("${DAY_HERO_DATA}");--pg4-hero-night:url("${NIGHT_HERO_DATA}")}
.pg4-hero{height:292px!important;background-color:#6d0d08!important;background-image:var(--pg4-hero-day)!important;background-size:cover!important;background-position:center 52%!important;background-repeat:no-repeat!important;border-bottom:1px solid #e6b95855!important}
html[data-hue-mode='dark'] .pg4-hero{background-color:#061827!important;background-image:var(--pg4-hero-night)!important;background-position:center 50%!important}
.pg4-hero-art{display:none!important}
.pg4-hero-shade{background:linear-gradient(180deg,rgba(42,2,2,.11) 0%,rgba(42,2,2,.005) 38%,rgba(42,2,2,.04) 72%,rgba(42,2,2,.30) 100%)!important}
html[data-hue-mode='dark'] .pg4-hero-shade{background:linear-gradient(180deg,rgba(1,7,12,.18) 0%,rgba(1,7,12,.005) 38%,rgba(2,9,15,.06) 72%,rgba(2,9,15,.34) 100%)!important}
.pg4-top{top:calc(env(safe-area-inset-top) + 8px)!important;left:15px!important;right:11px!important;align-items:flex-start!important}
.pg4-logo{width:72px!important;height:72px!important;filter:drop-shadow(0 4px 9px #2100007a) drop-shadow(0 0 6px #e7b84a55)!important}
.pg4-actions{gap:6px!important}.pg4-language{position:relative!important;height:35px!important;min-width:106px!important;padding:0 20px 0 8px!important;border-radius:11px!important;overflow:hidden!important}.pg4-language svg{display:none!important}.pg4-language:before{display:none!important}.pg4-language:after{content:'⌄'!important;position:absolute!important;right:7px!important;top:50%!important;transform:translateY(-56%)!important;color:#f1c96d!important;font-size:12px!important;line-height:1!important;pointer-events:none!important}.pg4-language select{width:86px!important;padding:0!important;border:0!important;background:transparent!important;color:inherit!important;font-size:10.2px!important;text-align:center!important;appearance:none!important;-webkit-appearance:none!important}.pg4-account,.pg4-bell{width:37px!important;height:37px!important}.pg4-account{font-size:15px!important}.pg4-bell svg{width:17px!important;height:17px!important}.pg4-bell b{min-width:14px!important;height:14px!important;font-size:7px!important}
.pg4-title{top:calc(env(safe-area-inset-top) + 76px)!important;left:86px!important;right:10px!important;text-align:center!important}.pg4-title h1{font-size:clamp(15.2px,4.2vw,18px)!important;line-height:1.04!important;letter-spacing:.022em!important;white-space:nowrap!important}.pg4-title p{margin:4px 0 4px!important;font-size:9px!important;white-space:nowrap!important}.pg4-divider{gap:5px!important;font-size:7px!important}.pg4-divider:before,.pg4-divider:after{width:29px!important}
.pg4-flow{margin-top:-8px!important;gap:8px!important;width:calc(100% - 20px)!important;max-width:520px!important}.pg4-sample{min-height:58px!important;padding:8px 36px 8px 49px!important;border-radius:13px!important;box-shadow:0 8px 20px #28000042,inset 0 1px #fff9!important}.pg4-sample:before,.pg4-sample:after{font-size:11px!important;top:2px!important}.pg4-sample-icon{left:11px!important;width:31px!important;height:31px!important}.pg4-sample-icon svg{width:19px!important;height:19px!important}.pg4-sample strong{margin-bottom:2px!important;font-size:10.3px!important;line-height:1.18!important}.pg4-sample p{font-size:8px!important;line-height:1.25!important}.pg4-sample>.pg4-chevron{right:9px!important;width:20px!important}
.pg4-overview{padding:46px 7px 9px!important;border-radius:15px!important;box-shadow:0 12px 26px #1f000050,inset 0 1px #fff2!important}.pg4-overview:before,.pg4-overview:after{top:4px!important;font-size:19px!important}.pg4-section-title{top:10px!important;font-size:10.4px!important;gap:5px!important}.pg4-section-title strong{padding:5px 11px!important}.pg4-section-title i{width:25px!important;height:8px!important}.pg4-section-title i:first-child:before,.pg4-section-title i:last-child:before{top:-7px!important}
.pg4-stats{gap:5px!important}.pg4-stat{min-height:96px!important;border-radius:12px!important;padding:8px 2px 7px!important;gap:4px!important;background-image:linear-gradient(180deg,#9f2a1ea0 0%,#5a0b07b2 55%,#380503e7 100%),var(--pg4-hero-day)!important;background-size:cover,210%!important;background-position:center,center 74%!important}.pg4-stat:before{inset:4px!important;border-radius:9px!important}.pg4-stat svg{width:19px!important;height:19px!important}.pg4-stat strong{font-size:24px!important}.pg4-stat.family strong{font-size:14.5px!important}.pg4-stat span{font-size:8px!important}html[data-hue-mode='dark'] .pg4-stat{background-image:linear-gradient(180deg,#173e55a0 0%,#092235b7 55%,#03101bea 100%),var(--pg4-hero-night)!important}
.pg4-tree{width:calc(100% - 6px)!important;height:46px!important;margin:9px auto 0!important;padding:0 42px 0 56px!important;border-radius:17px!important}.pg4-tree:before,.pg4-tree:after{width:29px!important;height:40px!important;font-size:14px!important}.pg4-tree:before{left:-6px!important}.pg4-tree:after{right:-6px!important}.pg4-tree>svg:first-of-type{left:16px!important;width:29px!important;height:29px!important;stroke-width:1.4!important;fill:#efc6622a!important;filter:drop-shadow(0 0 4px #efc66255)!important}.pg4-tree>svg:last-of-type{right:13px!important;width:20px!important}.pg4-tree strong{font-size:15px!important}
.pg4-quote{min-height:92px!important;padding:12px 30px 11px!important;border-radius:11px!important;font-size:12.2px!important;line-height:1.18!important;background-image:linear-gradient(90deg,#f2dfbabf,#f7e8cabf),var(--pg4-hero-day)!important;background-size:cover,115%!important;background-position:center,center 72%!important}.pg4-quote:before,.pg4-quote:after{width:8px!important;top:9px!important;bottom:9px!important}.pg4-quote small{margin-top:5px!important;font-size:11px!important}.pg4-lotus{left:17px!important;bottom:10px!important;font-size:19px!important;text-shadow:0 1px 0 #7c2b2b33!important}.pg4-gate{right:18px!important;bottom:8px!important;width:66px!important;height:37px!important;font-size:0!important;background-image:var(--pg4-hero-day)!important;background-size:150%!important;background-position:center 44%!important;background-repeat:no-repeat!important;opacity:.42!important;filter:sepia(.8) saturate(.55) contrast(.9)!important;clip-path:polygon(8% 100%,8% 40%,18% 40%,18% 24%,31% 24%,31% 10%,69% 10%,69% 24%,82% 24%,82% 40%,92% 40%,92% 100%)!important}html[data-hue-mode='dark'] .pg4-quote{background-image:linear-gradient(90deg,#e5d2a8c5,#d5c195c5),var(--pg4-hero-night)!important}html[data-hue-mode='dark'] .pg4-gate{background-image:var(--pg4-hero-night)!important}
.pg4-nav{height:calc(58px + env(safe-area-inset-bottom))!important;padding:3px 5px max(3px,env(safe-area-inset-bottom))!important}.pg4-nav button{font-size:7px!important;gap:2px!important}.pg4-nav button svg{width:17px!important;height:17px!important}.pg4-nav button.active:before{top:-3px!important;width:37px!important;height:3px!important}.pg4-nav button:first-child.active svg{fill:currentColor!important;stroke-width:1.35!important}
.pg-home-v4{padding-bottom:calc(60px + env(safe-area-inset-bottom))!important}
@media(max-width:390px){.pg4-hero{height:276px!important}.pg4-logo{width:68px!important;height:68px!important}.pg4-title{top:calc(env(safe-area-inset-top) + 71px)!important;left:80px!important}.pg4-title h1{font-size:14.4px!important}.pg4-title p{font-size:8.4px!important}.pg4-language{min-width:98px!important}.pg4-language select{width:78px!important}.pg4-account,.pg4-bell{width:35px!important;height:35px!important}.pg4-sample{min-height:55px!important}.pg4-overview{padding-top:44px!important}.pg4-stat{min-height:92px!important}.pg4-tree{height:44px!important}.pg4-quote{min-height:86px!important}}
  `}</style>;
}
