'use client';

import { DAY_HERO_DATA, NIGHT_HERO_DATA } from './overview-hero-data.generated';

export default function OverviewV5Tune() {
  return <style>{`
/* V12: geometry is derived from the approved 480px-wide reference screen. Artwork stays fully in-bundle. */
html{--pg4-hero-day:url("${DAY_HERO_DATA}");--pg4-hero-night:url("${NIGHT_HERO_DATA}")}
.pg4-hero{height:107vw!important;min-height:390px!important;max-height:430px!important;background-color:#6d0d08!important;background-image:var(--pg4-hero-day)!important;background-size:cover!important;background-position:center 50%!important;background-repeat:no-repeat!important;border-bottom:1px solid #e6b95855!important}
html[data-hue-mode='dark'] .pg4-hero{background-color:#061827!important;background-image:var(--pg4-hero-night)!important;background-position:center 50%!important}
.pg4-hero-art{display:none!important}.pg4-hero-shade{background:linear-gradient(180deg,rgba(42,2,2,.08),rgba(42,2,2,0) 42%,rgba(42,2,2,.02) 70%,rgba(42,2,2,.22))!important}html[data-hue-mode='dark'] .pg4-hero-shade{background:linear-gradient(180deg,rgba(1,7,12,.14),rgba(1,7,12,0) 42%,rgba(2,9,15,.04) 70%,rgba(2,9,15,.28))!important}
.pg4-top{top:calc(env(safe-area-inset-top) + 9px)!important;left:13px!important;right:9px!important;align-items:flex-start!important}.pg4-logo{width:96px!important;height:96px!important;filter:drop-shadow(0 5px 11px #21000070) drop-shadow(0 0 7px #e7b84a55)!important}.pg4-actions{gap:6px!important;padding-top:3px!important}.pg4-language{position:relative!important;height:36px!important;min-width:120px!important;padding:0 20px 0 8px!important;border-radius:12px!important;overflow:hidden!important}.pg4-language svg,.pg4-language:before{display:none!important}.pg4-language:after{content:'⌄'!important;position:absolute!important;right:7px!important;top:50%!important;transform:translateY(-56%)!important;color:#f1c96d!important;font-size:13px!important;line-height:1!important;pointer-events:none!important}.pg4-language select{width:100px!important;padding:0!important;border:0!important;background:transparent!important;color:inherit!important;font-size:11.5px!important;text-align:center!important;appearance:none!important;-webkit-appearance:none!important}.pg4-account,.pg4-bell{width:41px!important;height:41px!important}.pg4-account{font-size:17px!important}.pg4-bell svg{width:19px!important;height:19px!important}.pg4-bell b{min-width:14px!important;height:14px!important;font-size:7px!important}
.pg4-title{top:calc(env(safe-area-inset-top) + 82px)!important;left:116px!important;right:7px!important;text-align:center!important}.pg4-title h1{font-size:clamp(19px,5.55vw,22.5px)!important;line-height:1.05!important;letter-spacing:.02em!important;white-space:nowrap!important}.pg4-title p{margin:6px 0 5px!important;font-size:12.2px!important;white-space:nowrap!important}.pg4-divider{gap:6px!important;font-size:8px!important}.pg4-divider:before,.pg4-divider:after{width:36px!important}
.pg4-flow{margin-top:-2px!important;gap:8px!important;width:calc(100% - 20px)!important;max-width:520px!important}.pg4-sample{min-height:80px!important;padding:11px 40px 11px 61px!important;border-radius:15px!important;box-shadow:0 8px 22px #28000042,inset 0 1px #fff9!important}.pg4-sample:before,.pg4-sample:after{font-size:12px!important;top:3px!important}.pg4-sample-icon{left:13px!important;width:40px!important;height:40px!important}.pg4-sample-icon svg{width:25px!important;height:25px!important}.pg4-sample strong{margin-bottom:3px!important;font-size:12.4px!important;line-height:1.2!important}.pg4-sample p{font-size:10.4px!important;line-height:1.28!important}.pg4-sample>.pg4-chevron{right:10px!important;width:22px!important}
.pg4-overview{padding:62px 9px 12px!important;border-radius:17px!important;box-shadow:0 12px 28px #1f000050,inset 0 1px #fff2!important}.pg4-overview:before,.pg4-overview:after{top:6px!important;font-size:22px!important}.pg4-section-title{top:15px!important;font-size:15.8px!important;gap:8px!important}.pg4-section-title strong{padding:7px 15px!important}.pg4-section-title i{width:33px!important;height:10px!important}.pg4-section-title i:first-child:before,.pg4-section-title i:last-child:before{top:-9px!important}
.pg4-stats{gap:7px!important}.pg4-stat{min-height:145px!important;border-radius:14px!important;padding:13px 3px 10px!important;gap:5px!important;background-image:linear-gradient(180deg,#9f2a1e8c 0%,#5a0b079a 48%,#380503df 100%),var(--pg4-hero-day)!important;background-size:cover,195%!important;background-position:center,center 73%!important}.pg4-stat:before{inset:5px!important;border-radius:10px!important}.pg4-stat svg{width:25px!important;height:25px!important}.pg4-stat strong{font-size:34px!important}.pg4-stat.family strong{font-size:19px!important;line-height:1.02!important}.pg4-stat span{font-size:10.5px!important}html[data-hue-mode='dark'] .pg4-stat{background-image:linear-gradient(180deg,#173e558e 0%,#092235a0 48%,#03101be5 100%),var(--pg4-hero-night)!important}
.pg4-tree{width:calc(100% - 8px)!important;height:74px!important;margin:12px auto 0!important;padding:0 48px 0 73px!important;border-radius:22px!important}.pg4-tree:before,.pg4-tree:after{width:39px!important;height:64px!important;font-size:17px!important}.pg4-tree:before{left:-8px!important}.pg4-tree:after{right:-8px!important}.pg4-tree>svg:first-of-type{left:19px!important;width:47px!important;height:47px!important;stroke-width:1.25!important;fill:#efc66222!important;filter:drop-shadow(0 0 5px #efc66266)!important}.pg4-tree>svg:last-of-type{right:15px!important;width:23px!important}.pg4-tree strong{font-size:22px!important}
.pg4-quote{min-height:140px!important;padding:20px 39px 18px!important;border-radius:12px!important;font-size:17.5px!important;line-height:1.2!important;background-image:linear-gradient(90deg,#f2dfbaa8,#f7e8caa8),var(--pg4-hero-day)!important;background-size:cover,116%!important;background-position:center,center 72%!important}.pg4-quote:before,.pg4-quote:after{width:10px!important;top:10px!important;bottom:10px!important}.pg4-quote small{margin-top:8px!important;font-size:13px!important}.pg4-lotus{left:19px!important;bottom:14px!important;font-size:25px!important}.pg4-gate{right:20px!important;bottom:10px!important;width:85px!important;height:52px!important;font-size:0!important;background-image:var(--pg4-hero-day)!important;background-size:150%!important;background-position:center 44%!important;background-repeat:no-repeat!important;opacity:.46!important;filter:sepia(.8) saturate(.55) contrast(.9)!important;clip-path:polygon(8% 100%,8% 40%,18% 40%,18% 24%,31% 24%,31% 10%,69% 10%,69% 24%,82% 24%,82% 40%,92% 40%,92% 100%)!important}html[data-hue-mode='dark'] .pg4-quote{background-image:linear-gradient(90deg,#e5d2a8ad,#d5c195ad),var(--pg4-hero-night)!important}html[data-hue-mode='dark'] .pg4-gate{background-image:var(--pg4-hero-night)!important}
.pg4-nav{height:calc(72px + env(safe-area-inset-bottom))!important;padding:5px 6px max(4px,env(safe-area-inset-bottom))!important}.pg4-nav button{font-size:9.6px!important;gap:3px!important}.pg4-nav button svg{width:22px!important;height:22px!important}.pg4-nav button.active:before{top:-5px!important;width:44px!important;height:3px!important}.pg4-nav button:first-child.active svg{fill:currentColor!important;stroke-width:1.35!important}.pg-home-v4{padding-bottom:calc(74px + env(safe-area-inset-bottom))!important}
@media(max-width:380px){.pg4-logo{width:90px!important;height:90px!important}.pg4-title{left:107px!important}.pg4-title h1{font-size:18.8px!important}.pg4-title p{font-size:11.3px!important}.pg4-language{min-width:110px!important}.pg4-language select{width:90px!important}.pg4-stat{min-height:138px!important}.pg4-tree{height:70px!important}.pg4-quote{min-height:134px!important}}
  `}</style>;
}
