'use client';
import { useEffect } from 'react';

export default function OverviewPremiumRedesign(){
  useEffect(()=>{
    let done=false;
    const openHome=()=>{
      if(done)return true;
      const shell=document.querySelector('.app-shell');
      if(!shell)return false;
      const buttons=Array.from(shell.querySelectorAll<HTMLButtonElement>('.tabs button'));
      const home=buttons.find((button)=>button.textContent?.toLocaleLowerCase('vi').includes('tổng quan'))??buttons[0];
      if(!home)return false;
      home.click();done=true;
      requestAnimationFrame(()=>{document.documentElement.dataset.homeReady='true';});
      return true;
    };
    const observer=new MutationObserver(()=>{if(openHome())observer.disconnect();});
    if(!openHome())observer.observe(document.body,{childList:true,subtree:true});
    return()=>observer.disconnect();
  },[]);

  return <style>{`
:root{--pg-red:#8e160f;--pg-red2:#550806;--pg-deep:#260302;--pg-gold:#d8aa49;--pg-hi:#ffe49b;--pg-text:#fff0c9;--pg-muted:#d0b493;--pg-shadow:#1800008c}
html[data-hue-mode='dark']{--pg-red:#12384e;--pg-red2:#081c2a;--pg-deep:#02090f;--pg-gold:#d1a34b;--pg-hi:#f4d587;--pg-text:#f4e5b6;--pg-muted:#aaa18e;--pg-shadow:#000b}
html:not([data-home-ready='true']) .app-shell{visibility:hidden}
.overview-view{position:relative!important;isolation:isolate;width:min(760px,calc(100% - 34px))!important;margin:18px auto 0!important;padding:70px 20px 24px!important;overflow:hidden;border:1px solid #d8aa4975!important;border-radius:24px!important;background:linear-gradient(145deg,#78140ef8,var(--pg-deep))!important;box-shadow:0 24px 60px var(--pg-shadow),inset 0 1px #ffe6a02b!important;text-align:center!important}
html[data-hue-mode='dark'] .overview-view{background:linear-gradient(145deg,#102e41f8,var(--pg-deep))!important}
.overview-view:before{content:'';position:absolute;z-index:-1;left:50%;top:51%;width:min(610px,116vw);aspect-ratio:1;transform:translate(-50%,-50%);border-radius:50%;background:radial-gradient(circle,transparent 0 9%,#d8aa4927 9.4% 10%,transparent 10.4% 18%,#d8aa4930 18.4% 19%,transparent 19.4% 29%,#d8aa4938 29.4% 30%,transparent 30.4% 41%,#d8aa4942 41.4% 42%,transparent 42.4%),repeating-conic-gradient(from 0deg,#d8aa492d 0 2deg,transparent 2deg 8deg,#d8aa491d 8deg 10deg,transparent 10deg 17deg);opacity:.78}
.overview-view:after{content:'TỔNG QUAN DÒNG HỌ';position:absolute;top:20px;left:50%;transform:translateX(-50%);min-width:260px;padding:9px 22px;border:1px solid var(--pg-gold);border-radius:999px;background:linear-gradient(180deg,#7a140e,#460604);color:var(--pg-hi);font-family:var(--font-serif),Georgia,serif;font-size:13px;font-weight:600;letter-spacing:.06em;white-space:nowrap;box-shadow:0 7px 22px #1d000066,inset 0 1px #fff3}
html[data-hue-mode='dark'] .overview-view:after{background:linear-gradient(180deg,#15384d,#07131e)}
.overview-stats{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:9px!important;margin:0!important;padding:0!important;border:0!important}.overview-stats:before{display:none!important}
.overview-stats>div{position:relative!important;display:flex!important;min-height:124px!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:7px!important;padding:25px 5px 13px!important;overflow:hidden;border:1px solid #dfb45788!important;border-radius:17px!important;background:linear-gradient(158deg,#a12b1fc9,#390504eb)!important;box-shadow:0 12px 26px #1a00006b,inset 0 1px #ffeaa52d!important}
html[data-hue-mode='dark'] .overview-stats>div{background:linear-gradient(158deg,#173c53d8,#06111bec)!important}
.overview-stats>div:before{position:absolute!important;top:9px!important;color:#f0c96ecc!important;font-size:14px!important}.overview-stats>div:nth-child(1):before{content:'♟'!important}.overview-stats>div:nth-child(2):before{content:'✣'!important}.overview-stats>div:nth-child(3):before{content:'▤'!important}.overview-stats>div:after{content:''!important;position:absolute!important;inset:5px!important;border:1px solid #d8aa492a!important;border-radius:13px!important}
.overview-stats strong{position:relative;z-index:2;color:var(--pg-hi)!important;font-family:var(--font-serif),Georgia,serif!important;font-size:30px!important;font-weight:600!important;line-height:1!important;text-shadow:0 2px 12px #0006!important}.overview-stats>div:nth-child(3) strong{max-width:105px;font-size:17px!important;line-height:1.1!important;letter-spacing:.04em!important}.overview-stats span{position:relative;z-index:2;color:var(--pg-muted)!important;font-size:10px!important}
.overview-view>button{position:relative!important;width:100%!important;height:60px!important;margin:19px auto 0!important;padding:0 58px!important;border:1px solid var(--pg-hi)!important;border-radius:20px!important;background:linear-gradient(180deg,#c13a28,#81140e)!important;color:var(--pg-hi)!important;font-family:var(--font-serif),Georgia,serif!important;font-size:18px!important;font-weight:600!important;box-shadow:0 12px 28px #2100007d,inset 0 1px #fff5!important}.overview-view>button:before{content:'♧'!important;position:absolute!important;left:20px!important;top:50%!important;width:33px!important;height:33px!important;display:grid!important;place-items:center!important;transform:translateY(-50%)!important;border:1px solid #e7bd5d!important;border-radius:50%!important;font-size:21px!important}.overview-view>button:after{content:'›'!important;position:absolute!important;right:22px!important;top:50%!important;transform:translateY(-54%)!important;font-family:Arial,sans-serif!important;font-size:30px!important}html[data-hue-mode='dark'] .overview-view>button{background:linear-gradient(180deg,#1b4864,#091b29)!important}
@media(max-width:740px){
html,body{background:var(--pg-deep)!important}.app-shell:has(.overview-view){height:100dvh!important;min-height:100dvh!important;overflow:hidden!important;background:var(--pg-deep)!important}.app-shell:has(.overview-view) .workspace{height:100dvh!important;display:block!important}.app-shell:has(.overview-view) .filter-panel{display:none!important}.app-shell:has(.overview-view) .content{width:100%!important;height:100dvh!important;display:block!important;overflow-x:hidden!important;overflow-y:auto!important;padding:0 0 calc(94px + env(safe-area-inset-bottom))!important;background:linear-gradient(180deg,#a12b1d 0%,#85150e 33%,#500806 70%,#250302 100%)!important;scrollbar-width:none!important;overscroll-behavior-y:contain!important}.app-shell:has(.overview-view) .content::-webkit-scrollbar{display:none!important}.app-shell:has(.overview-view) .content:before{display:none!important}html[data-hue-mode='dark'] .app-shell:has(.overview-view) .content{background:linear-gradient(180deg,#12364b 0%,#0b2638 38%,#071722 72%,#02080d 100%)!important}
.app-shell:has(.overview-view) .topbar{position:fixed!important;z-index:90!important;top:0!important;left:0!important;right:0!important;height:calc(66px + env(safe-area-inset-top))!important;padding:calc(env(safe-area-inset-top) + 10px) 14px 8px!important;display:flex!important;align-items:center!important;justify-content:flex-end!important;gap:9px!important;border:0!important;background:linear-gradient(180deg,#220302c2 0%,#22030255 58%,transparent 100%)!important;box-shadow:none!important}.app-shell:has(.overview-view) .topbar:after,.app-shell:has(.overview-view) .topbar .brand,.app-shell:has(.overview-view) .mobile-menu{display:none!important}html[data-hue-mode='dark'] .app-shell:has(.overview-view) .topbar{background:linear-gradient(180deg,#02080ccc 0%,#02080c60 58%,transparent 100%)!important}
.app-shell:has(.overview-view) .language-select{position:relative!important;display:flex!important;align-items:center!important;gap:7px!important;width:auto!important;height:38px!important;margin:0!important;padding:0 10px!important;border:1px solid #e0b14e9a!important;border-radius:13px!important;background:#520b08c7!important;backdrop-filter:blur(12px)!important;-webkit-backdrop-filter:blur(12px)!important}.app-shell:has(.overview-view) .language-select:before{content:'🇻🇳';font-size:14px}.app-shell:has(.overview-view) .language-select svg{display:none!important}.app-shell:has(.overview-view) .language-select select{width:auto!important;min-width:82px!important;padding:0 16px 0 0!important;border:0!important;background:transparent!important;box-shadow:none!important;color:var(--pg-text)!important;font-size:12px!important}.app-shell:has(.overview-view) .account-menu{margin:0!important}.app-shell:has(.overview-view) .profile{width:42px!important;height:42px!important;margin:0!important;border:1px solid #e2b351!important;background:linear-gradient(145deg,#8e1a11,#570906)!important;color:var(--pg-hi)!important;font-family:var(--font-serif),Georgia,serif!important;font-size:16px!important;box-shadow:0 5px 18px #13000055,inset 0 1px #fff3!important}html[data-hue-mode='dark'] .app-shell:has(.overview-view) .language-select{background:#07131ccf!important}html[data-hue-mode='dark'] .app-shell:has(.overview-view) .profile{background:linear-gradient(145deg,#173a50,#07131d)!important}
.tabs{position:fixed!important;z-index:110!important;left:0!important;right:0!important;bottom:0!important;top:auto!important;width:100%!important;height:calc(70px + env(safe-area-inset-bottom))!important;padding:7px 5px calc(6px + env(safe-area-inset-bottom))!important;display:grid!important;grid-template-columns:repeat(6,minmax(0,1fr))!important;gap:0!important;border-top:1px solid #d8a94b85!important;background:linear-gradient(180deg,#3a0604f4,#1d0202fb)!important;box-shadow:0 -12px 34px #16000078!important;backdrop-filter:blur(18px)!important;-webkit-backdrop-filter:blur(18px)!important}html[data-hue-mode='dark'] .tabs{background:linear-gradient(180deg,#07141ef5,#02080dfb)!important;border-top-color:#c89b4968!important;box-shadow:0 -12px 34px #0009!important}.tabs button{min-width:0!important;height:56px!important;padding:6px 2px 3px!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:3px!important;border:0!important;background:transparent!important;color:#d8c4ad!important;font-size:8.4px!important;line-height:1.05!important}.tabs button svg{display:block!important;width:20px!important;height:20px!important;stroke-width:1.7!important}.tabs button.active{color:var(--pg-hi)!important;text-shadow:0 0 12px #f4c95b55!important}.tabs button.active svg{filter:drop-shadow(0 0 5px #f5cb6290)}.bottom-tab-gold-line{top:1px!important;width:30px!important;height:2px!important}
.content:has(.overview-view)>.tab-brand,.content:has(.overview-view)>.tab-fallback-brand{position:relative!important;isolation:isolate!important;width:100%!important;min-height:430px!important;margin:0!important;padding:96px 20px 198px!important;display:grid!important;grid-template-columns:86px minmax(0,1fr)!important;grid-template-rows:auto auto!important;align-content:start!important;align-items:center!important;column-gap:14px!important;row-gap:3px!important;overflow:hidden!important;border:0!important;border-radius:0!important;background:radial-gradient(circle at 79% 31%,#ffd980 0 6.5%,#f7bb6a99 7%,transparent 17%),linear-gradient(180deg,#d96e45 0%,#b33926 34%,#8d1a11 62%,#3b0503 100%)!important;text-align:left!important;box-shadow:none!important}html[data-hue-mode='dark'] .content:has(.overview-view)>.tab-brand,html[data-hue-mode='dark'] .content:has(.overview-view)>.tab-fallback-brand{background:radial-gradient(circle at 80% 29%,#f5d78d 0 5.8%,#d7aa5055 6.3%,transparent 15%),linear-gradient(180deg,#12384f 0%,#0d2b3e 35%,#081b29 63%,#02090f 100%)!important}
.content:has(.overview-view)>.tab-brand:before,.content:has(.overview-view)>.tab-fallback-brand:before{content:''!important;position:absolute!important;z-index:-1!important;left:-8%!important;right:-8%!important;bottom:0!important;height:235px!important;background:linear-gradient(180deg,transparent 0 55%,#160202dc 56% 100%),linear-gradient(152deg,transparent 0 28%,#d8aa4a26 29% 30%,transparent 31% 43%,#e0b95b24 44% 46%,transparent 47%)!important;clip-path:polygon(0 82%,7% 65%,15% 72%,23% 49%,31% 61%,40% 37%,49% 54%,58% 32%,67% 51%,76% 30%,84% 58%,92% 45%,100% 62%,100% 100%,0 100%)!important}.content:has(.overview-view)>.tab-brand:after,.content:has(.overview-view)>.tab-fallback-brand:after{content:'✦   GÌN GIỮ CỘI NGUỒN   ✦'!important;position:absolute!important;z-index:3!important;left:50%!important;bottom:40px!important;transform:translateX(-50%)!important;color:#f5d781!important;font-family:var(--font-serif),Georgia,serif!important;font-size:9px!important;letter-spacing:.16em!important;white-space:nowrap!important;text-shadow:0 2px 8px #0009!important}.content:has(.overview-view)>.tab-brand>*{position:relative!important;z-index:4!important}.content:has(.overview-view)>.tab-brand .tab-brand-logo{grid-row:1/3!important;width:86px!important;height:86px!important;margin:0!important;padding:0!important;border:0!important;background:transparent!important;filter:drop-shadow(0 5px 12px #2500007a) drop-shadow(0 0 8px #edbe4e42)!important}.content:has(.overview-view)>.tab-brand .tab-brand-image{width:100%!important;height:100%!important;object-fit:contain!important}.content:has(.overview-view)>.tab-brand .system-name,.content:has(.overview-view)>.tab-fallback-brand .system-name{align-self:end!important;margin:0!important;color:#ffe397!important;font-family:var(--font-serif),Georgia,serif!important;font-size:20px!important;font-weight:600!important;line-height:1.15!important;letter-spacing:.035em!important;text-shadow:0 2px 12px #3900008f!important}.content:has(.overview-view)>.tab-brand p,.content:has(.overview-view)>.tab-fallback-brand p{align-self:start!important;margin:3px 0 0!important;color:#f2d6aa!important;font-size:10px!important;text-shadow:0 2px 9px #3900008f!important}
.content:has(.overview-view)>.sample-data-banner{position:relative!important;z-index:14!important;width:calc(100% - 28px)!important;max-width:none!important;min-height:86px!important;margin:-31px 14px 0!important;padding:14px 42px 14px 58px!important;display:flex!important;align-items:center!important;gap:10px!important;border:1px solid #e1b6579c!important;border-radius:16px!important;background:linear-gradient(135deg,#730f0af6,#390504f8)!important;box-shadow:0 14px 30px #1b000080,inset 0 1px #ffe69a24!important;color:var(--pg-text)!important}html[data-hue-mode='dark'] .content:has(.overview-view)>.sample-data-banner{background:linear-gradient(135deg,#102f43f8,#06131df8)!important}.content:has(.overview-view)>.sample-data-banner>svg{position:absolute!important;left:16px!important;top:50%!important;transform:translateY(-50%)!important;width:30px!important;height:30px!important;color:#f0c660!important}.content:has(.overview-view)>.sample-data-banner:after{content:'›'!important;position:absolute!important;right:16px!important;top:50%!important;transform:translateY(-54%)!important;color:#ffe39a!important;font-family:Arial,sans-serif!important;font-size:30px!important}.content:has(.overview-view) .sample-data-copy strong{display:block!important;margin:0 0 5px!important;color:#ffe8b0!important;font-size:12px!important;line-height:1.25!important}.content:has(.overview-view) .sample-data-copy p{margin:0!important;color:#d9c2a5!important;font-size:10px!important;line-height:1.5!important}
.overview-view{width:calc(100% - 28px)!important;max-width:none!important;margin:14px 14px 0!important;padding:68px 12px 21px!important;border-radius:20px!important}.overview-view:after{top:17px!important;min-width:236px!important;padding:8px 16px!important;font-size:12px!important}.overview-view:before{width:125vw!important;max-width:560px!important}.overview-stats{gap:7px!important}.overview-stats>div{min-height:114px!important;padding:24px 4px 12px!important;border-radius:15px!important}.overview-stats strong{font-size:27px!important}.overview-stats>div:nth-child(3) strong{font-size:15px!important}.overview-stats span{font-size:9px!important}.overview-view>button{height:57px!important;margin-top:17px!important;font-size:17px!important}
.content:has(.overview-view):after{content:'“Uống nước nhớ nguồn\\A Ăn quả nhớ kẻ trồng cây”'!important;white-space:pre-line!important;display:flex!important;align-items:center!important;justify-content:center!important;width:calc(100% - 28px)!important;min-height:148px!important;margin:14px 14px 0!important;padding:25px 36px!important;border:1px solid #d0a558b0!important;border-radius:14px!important;background:radial-gradient(circle at 15% 78%,#d8615b60 0 3%,transparent 3.5%),linear-gradient(180deg,#f0dfb9,#d8be8a)!important;box-shadow:0 12px 28px #1b00006a,inset 0 0 0 5px #7c3c1712!important;color:#4e2819!important;font-family:var(--font-serif),Georgia,serif!important;font-size:17px!important;font-style:italic!important;font-weight:500!important;line-height:1.65!important;text-align:center!important;text-shadow:none!important}html[data-hue-mode='dark'] .content:has(.overview-view):after{background:linear-gradient(180deg,#d9c99f,#bba77e)!important;color:#26323a!important}
}
@media(max-width:390px){.content:has(.overview-view)>.tab-brand,.content:has(.overview-view)>.tab-fallback-brand{grid-template-columns:74px minmax(0,1fr)!important;padding-left:16px!important;padding-right:16px!important}.content:has(.overview-view)>.tab-brand .tab-brand-logo{width:74px!important;height:74px!important}.content:has(.overview-view)>.tab-brand .system-name,.content:has(.overview-view)>.tab-fallback-brand .system-name{font-size:18px!important}.tabs button{font-size:7.7px!important}.tabs button svg{width:19px!important;height:19px!important}}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{transition:none!important;animation-duration:.001ms!important}}
  `}</style>;
}
