export type Language = 'vi' | 'en' | 'fr' | 'zh' | 'ru' | 'ja' | 'de';

export const languageNames: Record<Language, string> = { vi: '🇻🇳 Tiếng Việt', en: '🇬🇧 English', fr: '🇫🇷 Français', zh: '🇨🇳 中文', ru: '🇷🇺 Русский', ja: '🇯🇵 日本語', de: '🇩🇪 Deutsch' };

export const supportedLanguages: Language[] = ['vi', 'en', 'fr', 'zh', 'ru', 'ja', 'de'];

export const systemNames: Record<Language, string> = {
  vi: 'GIA PHẢ HỌ PHẠM VĂN',
  en: 'THE PHAM VAN GENEALOGY',
  fr: 'GÉNÉALOGIE DE LA FAMILLE PHẠM VĂN',
  zh: 'PHẠM VĂN 家族族谱',
  ru: 'РОДОСЛОВНАЯ СЕМЬИ PHẠM VĂN',
  ja: 'PHẠM VĂN 家の系譜',
  de: 'GENEALOGIE DER FAMILIE PHẠM VĂN',
};

const messages = {
  vi: ['Chào mừng','Chọn cách bạn muốn truy cập','Tạo tài khoản để quản lý đầy đủ gia phả, hoặc tiếp tục với quyền khách chỉ xem.','Tạo tài khoản nội bộ','Đăng ký riêng trong ứng dụng Gia phả họ Phạm Văn','Toàn quyền sử dụng','Khách tham quan','Không cần tài khoản, chỉ xem nội dung','Quyền chỉ xem','Tiếp tục với vai trò khách?','Khách tham quan chỉ được xem cây gia phả và không thể mở Cài đặt hoặc chỉnh sửa dữ liệu.','Quay lại','Tôi hiểu, tiếp tục xem','Tài khoản nội bộ','Tạo tài khoản mới','Đăng nhập','Họ và tên','Tên đăng nhập','Mật khẩu','Đang xử lý…','Đã có tài khoản? Đăng nhập','Chưa có tài khoản? Đăng ký ngay','Bạn đang xem với vai trò khách — chỉ có quyền xem','Tìm thành viên','Hiển thị theo đời','Tất cả các đời','Chú thích','Cây gia phả','Cài đặt','Quản trị hệ thống','Quản lý bản sao lưu và dữ liệu gia phả được lưu trên thiết bị này.','Chế độ hiển thị','Chọn giao diện phù hợp với thiết bị. Cây gia phả sẽ tự động thu phóng vừa vùng hiển thị.','Tự động','Desktop','Mobile','Ngôn ngữ','Chọn ngôn ngữ hiển thị của ứng dụng.','Chức năng dành cho tài khoản','Khách không có quyền mở Cài đặt hoặc chỉnh sửa dữ liệu.','Tiếp tục xem'],
  en: ['Welcome','Choose how you want to access','Create an account to manage the family tree, or continue as a read-only guest.','Create internal account','Register directly in the Phạm Family Tree app','Full access','Visitor','No account required, view only','View only','Continue as a guest?','Visitors can only view the family tree and cannot open Settings or edit data.','Go back','I understand, continue','Internal account','Create a new account','Sign in','Full name','Username','Password','Processing…','Already have an account? Sign in','No account yet? Register','You are viewing as a guest — read-only access','Search members','Filter by generation','All generations','Legend','Family tree','Settings','System administration','Manage backups and family-tree data stored on this device.','Display mode','Choose a layout for your device. The family tree scales automatically to fit.','Auto','Desktop','Mobile','Language','Choose the application display language.','Account-only function','Guests cannot open Settings or edit data.','Continue viewing'],
  fr: ['Bienvenue','Choisissez votre mode d’accès','Créez un compte pour gérer la généalogie ou continuez comme visiteur en lecture seule.','Créer un compte interne','Inscription dans l’application Généalogie Phạm','Accès complet','Visiteur','Aucun compte requis, consultation uniquement','Lecture seule','Continuer comme visiteur ?','Les visiteurs peuvent seulement consulter l’arbre et ne peuvent pas modifier les données.','Retour','Je comprends, continuer','Compte interne','Créer un compte','Se connecter','Nom complet','Identifiant','Mot de passe','Traitement…','Déjà inscrit ? Se connecter','Pas encore de compte ? S’inscrire','Vous consultez en tant que visiteur — lecture seule','Rechercher un membre','Filtrer par génération','Toutes les générations','Légende','Arbre généalogique','Paramètres','Administration système','Gérez les sauvegardes et les données généalogiques.','Mode d’affichage','Choisissez une mise en page. L’arbre s’adapte automatiquement.','Auto','Bureau','Mobile','Langue','Choisissez la langue d’affichage.','Fonction réservée aux comptes','Les visiteurs ne peuvent pas ouvrir les paramètres ni modifier les données.','Continuer'],
  zh: ['欢迎','选择访问方式','创建账户以完整管理家谱，或以只读访客身份继续。','创建内部账户','在范氏家谱应用中注册','完整权限','访客','无需账户，仅可查看','只读','以访客身份继续？','访客只能查看家谱，无法打开设置或编辑数据。','返回','我已了解，继续查看','内部账户','创建新账户','登录','姓名','用户名','密码','处理中…','已有账户？登录','没有账户？立即注册','您正以访客身份查看 — 只读权限','搜索成员','按世代筛选','所有世代','图例','家谱树','设置','系统管理','管理备份和家谱数据。','显示模式','选择适合设备的布局，家谱会自动缩放。','自动','桌面版','移动版','语言','选择应用显示语言。','账户专属功能','访客不能打开设置或编辑数据。','继续查看'],
  ru: ['Добро пожаловать','Выберите способ доступа','Создайте аккаунт для управления родословной или продолжите как гость только для просмотра.','Создать внутренний аккаунт','Регистрация в приложении рода Фам','Полный доступ','Гость','Без аккаунта, только просмотр','Только просмотр','Продолжить как гость?','Гости могут только просматривать древо и не могут менять настройки или данные.','Назад','Понятно, продолжить','Внутренний аккаунт','Создать аккаунт','Войти','Полное имя','Логин','Пароль','Обработка…','Уже есть аккаунт? Войти','Нет аккаунта? Регистрация','Гостевой режим — только просмотр','Поиск участников','Фильтр по поколению','Все поколения','Обозначения','Генеалогическое древо','Настройки','Управление системой','Управление резервными копиями и данными родословной.','Режим отображения','Выберите вид. Древо автоматически масштабируется.','Авто','Компьютер','Телефон','Язык','Выберите язык интерфейса.','Функция для аккаунта','Гости не могут открывать настройки или изменять данные.','Продолжить просмотр'],
  ja: ['ようこそ','アクセス方法を選択','アカウントを作成して家系図を管理するか、閲覧専用ゲストとして続行します。','内部アカウントを作成','ファム家系図アプリ内で登録','フルアクセス','ゲスト','アカウント不要、閲覧のみ','閲覧専用','ゲストとして続行しますか？','ゲストは家系図の閲覧のみ可能で、設定やデータを編集できません。','戻る','理解して続行','内部アカウント','新規アカウント作成','ログイン','氏名','ユーザー名','パスワード','処理中…','アカウントをお持ちですか？ログイン','アカウントがありませんか？登録','ゲストとして閲覧中 — 閲覧専用','メンバーを検索','世代で絞り込む','すべての世代','凡例','家系図','設定','システム管理','バックアップと家系データを管理します。','表示モード','端末に合う表示を選択。家系図は自動で拡大縮小します。','自動','デスクトップ','モバイル','言語','表示言語を選択します。','アカウント専用機能','ゲストは設定を開いたりデータを編集できません。','閲覧を続ける'],
  de: ['Willkommen','Zugriffsart auswählen','Erstellen Sie ein Konto zur Verwaltung oder fahren Sie als Gast mit Leserechten fort.','Internes Konto erstellen','Direkt in der Phạm-Stammbaum-App registrieren','Vollzugriff','Gast','Kein Konto erforderlich, nur ansehen','Nur lesen','Als Gast fortfahren?','Gäste können den Stammbaum nur ansehen und weder Einstellungen noch Daten bearbeiten.','Zurück','Verstanden, weiter','Internes Konto','Neues Konto erstellen','Anmelden','Vollständiger Name','Benutzername','Passwort','Wird verarbeitet…','Bereits registriert? Anmelden','Noch kein Konto? Registrieren','Gastmodus — nur Leserechte','Mitglieder suchen','Nach Generation filtern','Alle Generationen','Legende','Stammbaum','Einstellungen','Systemverwaltung','Sicherungen und Stammbaumdaten verwalten.','Anzeigemodus','Layout wählen. Der Stammbaum wird automatisch angepasst.','Automatisch','Desktop','Mobil','Sprache','Anzeigesprache der Anwendung wählen.','Nur für Konten','Gäste können Einstellungen oder Daten nicht bearbeiten.','Weiter ansehen'],
} satisfies Record<Language, string[]>;

export function translate(language: Language, index: number) { return messages[language][index] ?? messages.vi[index]; }

const tabTranslations: Record<Language, string[]> = {
  vi:['Tổng quan','Cây gia phả','Thành viên','Sự kiện','Tư liệu','Cài đặt'], en:['Overview','Family tree','Members','Events','Documents','Settings'], fr:['Aperçu','Arbre généalogique','Membres','Événements','Documents','Paramètres'], zh:['概览','家谱树','成员','事件','资料','设置'], ru:['Обзор','Родословная','Участники','События','Документы','Настройки'], ja:['概要','家系図','メンバー','行事','資料','設定'], de:['Übersicht','Stammbaum','Mitglieder','Ereignisse','Dokumente','Einstellungen'],
};
export function translateTab(language: Language, canonical: string) { const index = tabTranslations.vi.indexOf(canonical); return index < 0 ? canonical : tabTranslations[language][index]; }

const extra: Record<Exclude<Language,'vi'>, Record<string,string>> = {
  en:{'GIA PHẢ':'FAMILY TREE','HỌ PHẠM':'PHẠM FAMILY','Gìn giữ cội nguồn · Kết nối thế hệ':'Preserve roots · Connect generations','Ghi chú':'Notice','Ứng dụng hiện đang trong giai đoạn thử nghiệm. Khi phát hành chính thức, tài khoản cần hoàn tất Xác minh danh tính để mở khóa toàn bộ chức năng.':'The application is currently in testing. When officially released, accounts must complete Identity Verification to unlock all features.','Mật khẩu được mã hóa một chiều và không được lưu dưới dạng có thể đọc lại.':'Passwords are one-way encrypted and never stored in readable form.','DỰ ÁN':'PROJECT','Gia phả':'Genealogy','Dòng họ PHẠM':'PHẠM family','kết quả phù hợp':'matching results','thành viên':'members','thế hệ':'generations','Đời thứ':'Generation','Thủy tổ':'Founder','Thành viên dòng họ':'Family member','Chưa có dữ liệu gia phả':'No family-tree data','Dữ liệu trên thiết bị này đã được xóa.':'Data on this device has been deleted.','Đóng':'Close','Mở bộ lọc':'Open filters','Đóng bộ lọc':'Close filters','Xóa':'Clear','Thu nhỏ':'Zoom out','Phóng to':'Zoom in','Tự động vừa màn hình':'Fit to screen','Đăng xuất':'Sign out','Khách tham quan':'Visitor','Quản lý thành viên':'Member management','Mọi tài khoản nội bộ đều có thể thêm và sửa thành viên trong gia phả.':'Every internal account can add and edit family-tree members.','Sửa thành viên':'Edit member','Thêm thành viên':'Add member','Cập nhật thông tin hiển thị của thành viên.':'Update this member’s displayed information.','Thành viên mới sẽ được thêm vào nhánh đã chọn.':'The new member will be added to the selected branch.','Họ và tên thành viên':'Member full name','Vai trò / chú thích':'Role / note','Ví dụ: Trưởng chi':'Example: Branch head','Thêm vào nhánh của':'Add to the branch of','Lưu thay đổi':'Save changes','Thêm vào gia phả':'Add to family tree','Hủy':'Cancel','Sửa':'Edit','Vui lòng chọn một người thuộc gia phả.':'Please select a family-tree member.','Không thể lưu thay đổi.':'Unable to save changes.','Khách tham quan chỉ có thể xem thông tin thành viên trong cây gia phả.':'Visitors can view member information only in the family tree.'},
  fr:{'GIA PHẢ':'GÉNÉALOGIE','HỌ PHẠM':'FAMILLE PHẠM','Gìn giữ cội nguồn · Kết nối thế hệ':'Préserver les racines · Relier les générations','Ghi chú':'Remarque','Ứng dụng hiện đang trong giai đoạn thử nghiệm. Khi phát hành chính thức, tài khoản cần hoàn tất Xác minh danh tính để mở khóa toàn bộ chức năng.':'L’application est en phase de test. À sa sortie officielle, le compte devra terminer la vérification d’identité pour déverrouiller toutes les fonctions.','Mật khẩu được mã hóa một chiều và không được lưu dưới dạng có thể đọc lại.':'Les mots de passe sont chiffrés à sens unique et ne sont jamais stockés en clair.','DỰ ÁN':'PROJET','Gia phả':'Généalogie','Dòng họ PHẠM':'Famille PHẠM','kết quả phù hợp':'résultats','thành viên':'membres','thế hệ':'générations','Đời thứ':'Génération','Thủy tổ':'Fondateur','Thành viên dòng họ':'Membre de la famille','Chưa có dữ liệu gia phả':'Aucune donnée généalogique','Dữ liệu trên thiết bị này đã được xóa.':'Les données de cet appareil ont été supprimées.','Đóng':'Fermer','Mở bộ lọc':'Ouvrir les filtres','Đóng bộ lọc':'Fermer les filtres','Xóa':'Effacer','Thu nhỏ':'Réduire','Phóng to':'Agrandir','Tự động vừa màn hình':'Ajuster à l’écran','Đăng xuất':'Déconnexion','Khách tham quan':'Visiteur','Quản lý thành viên':'Gestion des membres','Mọi tài khoản nội bộ đều có thể thêm và sửa thành viên trong gia phả.':'Tous les comptes internes peuvent ajouter et modifier les membres.','Sửa thành viên':'Modifier le membre','Thêm thành viên':'Ajouter un membre','Cập nhật thông tin hiển thị của thành viên.':'Mettre à jour les informations affichées du membre.','Thành viên mới sẽ được thêm vào nhánh đã chọn.':'Le nouveau membre sera ajouté à la branche sélectionnée.','Họ và tên thành viên':'Nom complet du membre','Vai trò / chú thích':'Rôle / note','Ví dụ: Trưởng chi':'Exemple : chef de branche','Thêm vào nhánh của':'Ajouter à la branche de','Lưu thay đổi':'Enregistrer','Thêm vào gia phả':'Ajouter à la généalogie','Hủy':'Annuler','Sửa':'Modifier','Vui lòng chọn một người thuộc gia phả.':'Veuillez sélectionner un membre de la généalogie.','Không thể lưu thay đổi.':'Impossible d’enregistrer les modifications.','Khách tham quan chỉ có thể xem thông tin thành viên trong cây gia phả.':'Les visiteurs peuvent seulement consulter les membres dans l’arbre.'},
  zh:{'GIA PHẢ':'家谱','HỌ PHẠM':'PHẠM 家族','Gìn giữ cội nguồn · Kết nối thế hệ':'传承根脉 · 联结世代','Ghi chú':'提示','Ứng dụng hiện đang trong giai đoạn thử nghiệm. Khi phát hành chính thức, tài khoản cần hoàn tất Xác minh danh tính để mở khóa toàn bộ chức năng.':'应用目前处于测试阶段。正式发布后，账户须完成身份验证才能解锁全部功能。','Mật khẩu được mã hóa một chiều và không được lưu dưới dạng có thể đọc lại.':'密码采用单向加密，不会以可读形式保存。','DỰ ÁN':'项目','Gia phả':'家谱','Dòng họ PHẠM':'PHẠM 家族','kết quả phù hợp':'个匹配结果','thành viên':'位成员','thế hệ':'代','Đời thứ':'第','Thủy tổ':'始祖','Thành viên dòng họ':'家族成员','Chưa có dữ liệu gia phả':'暂无家谱数据','Dữ liệu trên thiết bị này đã được xóa.':'此设备上的数据已删除。','Đóng':'关闭','Mở bộ lọc':'打开筛选','Đóng bộ lọc':'关闭筛选','Xóa':'清除','Thu nhỏ':'缩小','Phóng to':'放大','Tự động vừa màn hình':'适合屏幕','Đăng xuất':'退出登录','Khách tham quan':'访客','Quản lý thành viên':'成员管理','Mọi tài khoản nội bộ đều có thể thêm và sửa thành viên trong gia phả.':'所有内部账户均可添加和编辑家谱成员。','Sửa thành viên':'编辑成员','Thêm thành viên':'添加成员','Cập nhật thông tin hiển thị của thành viên.':'更新成员的显示信息。','Thành viên mới sẽ được thêm vào nhánh đã chọn.':'新成员将添加到所选分支。','Họ và tên thành viên':'成员姓名','Vai trò / chú thích':'角色 / 备注','Ví dụ: Trưởng chi':'示例：支系负责人','Thêm vào nhánh của':'添加到该成员分支','Lưu thay đổi':'保存更改','Thêm vào gia phả':'添加到家谱','Hủy':'取消','Sửa':'编辑','Vui lòng chọn một người thuộc gia phả.':'请选择一位家谱成员。','Không thể lưu thay đổi.':'无法保存更改。','Khách tham quan chỉ có thể xem thông tin thành viên trong cây gia phả.':'访客只能在家谱树中查看成员信息。'},
  ru:{'GIA PHẢ':'РОДОСЛОВНАЯ','HỌ PHẠM':'РОД PHẠМ','Gìn giữ cội nguồn · Kết nối thế hệ':'Храним корни · Связываем поколения','Ghi chú':'Примечание','Ứng dụng hiện đang trong giai đoạn thử nghiệm. Khi phát hành chính thức, tài khoản cần hoàn tất Xác minh danh tính để mở khóa toàn bộ chức năng.':'Приложение проходит тестирование. После официального выпуска потребуется проверка личности для доступа ко всем функциям.','Mật khẩu được mã hóa một chiều và không được lưu dưới dạng có thể đọc lại.':'Пароли шифруются необратимо и не хранятся в читаемом виде.','DỰ ÁN':'ПРОЕКТ','Gia phả':'Родословная','Dòng họ PHẠM':'Род PHẠМ','kết quả phù hợp':'совпадений','thành viên':'участников','thế hệ':'поколения','Đời thứ':'Поколение','Thủy tổ':'Основатель','Thành viên dòng họ':'Член рода','Chưa có dữ liệu gia phả':'Нет данных родословной','Dữ liệu trên thiết bị này đã được xóa.':'Данные на этом устройстве удалены.','Đóng':'Закрыть','Mở bộ lọc':'Открыть фильтры','Đóng bộ lọc':'Закрыть фильтры','Xóa':'Очистить','Thu nhỏ':'Уменьшить','Phóng to':'Увеличить','Tự động vừa màn hình':'По размеру экрана','Đăng xuất':'Выйти','Khách tham quan':'Гость','Quản lý thành viên':'Управление участниками','Mọi tài khoản nội bộ đều có thể thêm và sửa thành viên trong gia phả.':'Все внутренние аккаунты могут добавлять и редактировать участников рода.','Sửa thành viên':'Изменить участника','Thêm thành viên':'Добавить участника','Cập nhật thông tin hiển thị của thành viên.':'Обновить отображаемые данные участника.','Thành viên mới sẽ được thêm vào nhánh đã chọn.':'Новый участник будет добавлен в выбранную ветвь.','Họ và tên thành viên':'Полное имя участника','Vai trò / chú thích':'Роль / примечание','Ví dụ: Trưởng chi':'Пример: глава ветви','Thêm vào nhánh của':'Добавить в ветвь','Lưu thay đổi':'Сохранить изменения','Thêm vào gia phả':'Добавить в родословную','Hủy':'Отмена','Sửa':'Изменить','Vui lòng chọn một người thuộc gia phả.':'Выберите участника родословной.','Không thể lưu thay đổi.':'Не удалось сохранить изменения.','Khách tham quan chỉ có thể xem thông tin thành viên trong cây gia phả.':'Гости могут просматривать участников только в древе.'},
  ja:{'GIA PHẢ':'家系図','HỌ PHẠM':'PHẠM 家','Gìn giữ cội nguồn · Kết nối thế hệ':'ルーツを守り · 世代をつなぐ','Ghi chú':'お知らせ','Ứng dụng hiện đang trong giai đoạn thử nghiệm. Khi phát hành chính thức, tài khoản cần hoàn tất Xác minh danh tính để mở khóa toàn bộ chức năng.':'アプリは現在テスト中です。正式リリース後、全機能を利用するには本人確認が必要です。','Mật khẩu được mã hóa một chiều và không được lưu dưới dạng có thể đọc lại.':'パスワードは一方向暗号化され、読める形では保存されません。','DỰ ÁN':'プロジェクト','Gia phả':'家系','Dòng họ PHẠM':'PHẠM 家','kết quả phù hợp':'件一致','thành viên':'名','thế hệ':'世代','Đời thứ':'第世代','Thủy tổ':'始祖','Thành viên dòng họ':'一族のメンバー','Chưa có dữ liệu gia phả':'家系データがありません','Dữ liệu trên thiết bị này đã được xóa.':'この端末のデータは削除されました。','Đóng':'閉じる','Mở bộ lọc':'フィルターを開く','Đóng bộ lọc':'フィルターを閉じる','Xóa':'クリア','Thu nhỏ':'縮小','Phóng to':'拡大','Tự động vừa màn hình':'画面に合わせる','Đăng xuất':'ログアウト','Khách tham quan':'ゲスト','Quản lý thành viên':'メンバー管理','Mọi tài khoản nội bộ đều có thể thêm và sửa thành viên trong gia phả.':'すべての内部アカウントは家系メンバーを追加・編集できます。','Sửa thành viên':'メンバーを編集','Thêm thành viên':'メンバーを追加','Cập nhật thông tin hiển thị của thành viên.':'メンバーの表示情報を更新します。','Thành viên mới sẽ được thêm vào nhánh đã chọn.':'新しいメンバーは選択した系統に追加されます。','Họ và tên thành viên':'メンバーの氏名','Vai trò / chú thích':'役割 / 注記','Ví dụ: Trưởng chi':'例：分家の代表','Thêm vào nhánh của':'次の系統に追加','Lưu thay đổi':'変更を保存','Thêm vào gia phả':'家系図に追加','Hủy':'キャンセル','Sửa':'編集','Vui lòng chọn một người thuộc gia phả.':'家系のメンバーを選択してください。','Không thể lưu thay đổi.':'変更を保存できません。','Khách tham quan chỉ có thể xem thông tin thành viên trong cây gia phả.':'ゲストは家系図でのみメンバー情報を閲覧できます。'},
  de:{'GIA PHẢ':'STAMMBAUM','HỌ PHẠM':'FAMILIE PHẠM','Gìn giữ cội nguồn · Kết nối thế hệ':'Wurzeln bewahren · Generationen verbinden','Ghi chú':'Hinweis','Ứng dụng hiện đang trong giai đoạn thử nghiệm. Khi phát hành chính thức, tài khoản cần hoàn tất Xác minh danh tính để mở khóa toàn bộ chức năng.':'Die Anwendung befindet sich in der Testphase. Nach der Veröffentlichung ist eine Identitätsprüfung erforderlich, um alle Funktionen freizuschalten.','Mật khẩu được mã hóa một chiều và không được lưu dưới dạng có thể đọc lại.':'Passwörter werden irreversibel verschlüsselt und nie lesbar gespeichert.','DỰ ÁN':'PROJEKT','Gia phả':'Genealogie','Dòng họ PHẠM':'Familie PHẠM','kết quả phù hợp':'Treffer','thành viên':'Mitglieder','thế hệ':'Generationen','Đời thứ':'Generation','Thủy tổ':'Gründer','Thành viên dòng họ':'Familienmitglied','Chưa có dữ liệu gia phả':'Keine Stammbaumdaten','Dữ liệu trên thiết bị này đã được xóa.':'Die Daten auf diesem Gerät wurden gelöscht.','Đóng':'Schließen','Mở bộ lọc':'Filter öffnen','Đóng bộ lọc':'Filter schließen','Xóa':'Löschen','Thu nhỏ':'Verkleinern','Phóng to':'Vergrößern','Tự động vừa màn hình':'An Bildschirm anpassen','Đăng xuất':'Abmelden','Khách tham quan':'Gast','Quản lý thành viên':'Mitgliederverwaltung','Mọi tài khoản nội bộ đều có thể thêm và sửa thành viên trong gia phả.':'Alle internen Konten können Familienmitglieder hinzufügen und bearbeiten.','Sửa thành viên':'Mitglied bearbeiten','Thêm thành viên':'Mitglied hinzufügen','Cập nhật thông tin hiển thị của thành viên.':'Angezeigte Informationen des Mitglieds aktualisieren.','Thành viên mới sẽ được thêm vào nhánh đã chọn.':'Das neue Mitglied wird dem gewählten Zweig hinzugefügt.','Họ và tên thành viên':'Vollständiger Name','Vai trò / chú thích':'Rolle / Hinweis','Ví dụ: Trưởng chi':'Beispiel: Zweigleiter','Thêm vào nhánh của':'Zum Zweig hinzufügen','Lưu thay đổi':'Änderungen speichern','Thêm vào gia phả':'Zum Stammbaum hinzufügen','Hủy':'Abbrechen','Sửa':'Bearbeiten','Vui lòng chọn một người thuộc gia phả.':'Bitte wählen Sie ein Familienmitglied.','Không thể lưu thay đổi.':'Änderungen konnten nicht gespeichert werden.','Khách tham quan chỉ có thể xem thông tin thành viên trong cây gia phả.':'Gäste können Mitgliedsdaten nur im Stammbaum ansehen.'}
};
const profileExtra: Record<Exclude<Language, 'vi'>, Record<string, string>> = {
  en: { 'Hồ sơ tài khoản': 'Account profile', 'Chế độ chỉ xem': 'Read-only mode', 'Quản trị cấp cao': 'Super administrator', 'Thành viên': 'Member', 'Quyền truy cập đầy đủ': 'Full access', 'Khách tham quan không thể chỉnh sửa hoặc cài đặt.': 'Visitors cannot edit data or use settings.', 'Đăng nhập hoặc tạo tài khoản': 'Sign in or create an account' },
  fr: { 'Hồ sơ tài khoản': 'Profil du compte', 'Chế độ chỉ xem': 'Mode lecture seule', 'Quản trị cấp cao': 'Administrateur principal', 'Thành viên': 'Membre', 'Quyền truy cập đầy đủ': 'Accès complet', 'Khách tham quan không thể chỉnh sửa hoặc cài đặt.': 'Les visiteurs ne peuvent ni modifier ni régler l’application.', 'Đăng nhập hoặc tạo tài khoản': 'Se connecter ou créer un compte' },
  zh: { 'Hồ sơ tài khoản': '账户资料', 'Chế độ chỉ xem': '只读模式', 'Quản trị cấp cao': '高级管理员', 'Thành viên': '成员', 'Quyền truy cập đầy đủ': '完整权限', 'Khách tham quan không thể chỉnh sửa hoặc cài đặt.': '访客不能编辑数据或使用设置。', 'Đăng nhập hoặc tạo tài khoản': '登录或创建账户' },
  ru: { 'Hồ sơ tài khoản': 'Профиль аккаунта', 'Chế độ chỉ xem': 'Режим просмотра', 'Quản trị cấp cao': 'Главный администратор', 'Thành viên': 'Участник', 'Quyền truy cập đầy đủ': 'Полный доступ', 'Khách tham quan không thể chỉnh sửa hoặc cài đặt.': 'Гости не могут изменять данные или настройки.', 'Đăng nhập hoặc tạo tài khoản': 'Войти или создать аккаунт' },
  ja: { 'Hồ sơ tài khoản': 'アカウントプロフィール', 'Chế độ chỉ xem': '閲覧専用モード', 'Quản trị cấp cao': '上級管理者', 'Thành viên': 'メンバー', 'Quyền truy cập đầy đủ': 'フルアクセス', 'Khách tham quan không thể chỉnh sửa hoặc cài đặt.': 'ゲストはデータや設定を編集できません。', 'Đăng nhập hoặc tạo tài khoản': 'ログインまたはアカウント作成' },
  de: { 'Hồ sơ tài khoản': 'Kontoprofil', 'Chế độ chỉ xem': 'Nur-Lese-Modus', 'Quản trị cấp cao': 'Hauptadministrator', 'Thành viên': 'Mitglied', 'Quyền truy cập đầy đủ': 'Vollzugriff', 'Khách tham quan không thể chỉnh sửa hoặc cài đặt.': 'Gäste können weder Daten noch Einstellungen bearbeiten.', 'Đăng nhập hoặc tạo tài khoản': 'Anmelden oder Konto erstellen' },
};

const memberExtra: Record<Exclude<Language, 'vi'>, Record<string, string>> = {
  en: { 'Ảnh đại diện': 'Profile photo', 'Đã chọn ảnh': 'Photo selected', 'Chọn ảnh dưới 240 KB': 'Choose an image under 240 KB', 'Ảnh đại diện cần là ảnh dưới 240 KB.': 'Profile photo must be an image under 240 KB.', 'Quan hệ': 'Relationship', 'Số căn cước': 'Identity number', 'Ngày sinh': 'Date of birth', 'Ngày mất': 'Date of death', 'Ngày dỗ': 'Memorial day', 'Ví dụ: Con trai trưởng': 'Example: Eldest son', 'Con của': 'Child of', 'Con cái': 'Children', 'Chưa có thông tin con cái.': 'No child information yet.', 'Hồ sơ thành viên': 'Member profile', 'Sửa hồ sơ thành viên': 'Edit member profile', 'Sự kiện gia đình': 'Family events', 'Ngày sinh nhật và ngày dỗ được lấy từ thông tin hồ sơ thành viên.': 'Birthdays and memorial days are taken from member profiles.', 'Sinh nhật': 'Birthday', 'Lặp lại hằng năm': 'Repeats annually', 'Chưa có sự kiện nào được cập nhật.': 'No events have been added yet.', 'Hãy thêm ngày sinh hoặc ngày mất và ngày dỗ trong hồ sơ thành viên.': 'Add a date of birth, or a date of death and memorial day to a member profile.' },
  fr: { 'Ảnh đại diện': 'Photo de profil', 'Đã chọn ảnh': 'Photo sélectionnée', 'Chọn ảnh dưới 240 KB': 'Choisir une image de moins de 240 Ko', 'Ảnh đại diện cần là ảnh dưới 240 KB.': 'La photo de profil doit faire moins de 240 Ko.', 'Quan hệ': 'Lien familial', 'Số căn cước': 'Numéro d’identité', 'Ngày sinh': 'Date de naissance', 'Ngày mất': 'Date de décès', 'Ngày dỗ': 'Jour commémoratif', 'Ví dụ: Con trai trưởng': 'Exemple : fils aîné', 'Con của': 'Enfant de', 'Con cái': 'Enfants', 'Chưa có thông tin con cái.': 'Aucune information sur les enfants.', 'Hồ sơ thành viên': 'Profil du membre', 'Sửa hồ sơ thành viên': 'Modifier le profil du membre', 'Sự kiện gia đình': 'Événements familiaux', 'Ngày sinh nhật và ngày dỗ được lấy từ thông tin hồ sơ thành viên.': 'Les anniversaires et jours commémoratifs proviennent des profils des membres.', 'Sinh nhật': 'Anniversaire', 'Lặp lại hằng năm': 'Se répète chaque année', 'Chưa có sự kiện nào được cập nhật.': 'Aucun événement n’a encore été ajouté.', 'Hãy thêm ngày sinh hoặc ngày mất và ngày dỗ trong hồ sơ thành viên.': 'Ajoutez une date de naissance, ou une date de décès et un jour commémoratif au profil d’un membre.' },
  zh: { 'Ảnh đại diện': '头像', 'Đã chọn ảnh': '已选择图片', 'Chọn ảnh dưới 240 KB': '选择小于 240 KB 的图片', 'Ảnh đại diện cần là ảnh dưới 240 KB.': '头像必须是小于 240 KB 的图片。', 'Quan hệ': '关系', 'Số căn cước': '身份证号码', 'Ngày sinh': '出生日期', 'Ngày mất': '逝世日期', 'Ngày dỗ': '忌日', 'Ví dụ: Con trai trưởng': '示例：长子', 'Con của': '之子', 'Con cái': '子女', 'Chưa có thông tin con cái.': '暂无子女信息。', 'Hồ sơ thành viên': '成员资料', 'Sửa hồ sơ thành viên': '编辑成员资料', 'Sự kiện gia đình': '家族活动', 'Ngày sinh nhật và ngày dỗ được lấy từ thông tin hồ sơ thành viên.': '生日和忌日来自成员资料。', 'Sinh nhật': '生日', 'Lặp lại hằng năm': '每年重复', 'Chưa có sự kiện nào được cập nhật.': '尚未添加任何活动。', 'Hãy thêm ngày sinh hoặc ngày mất và ngày dỗ trong hồ sơ thành viên.': '请在成员资料中添加出生日期，或逝世日期和忌日。' },
  ru: { 'Ảnh đại diện': 'Фото профиля', 'Đã chọn ảnh': 'Фото выбрано', 'Chọn ảnh dưới 240 KB': 'Выберите изображение до 240 КБ', 'Ảnh đại diện cần là ảnh dưới 240 KB.': 'Фото профиля должно быть меньше 240 КБ.', 'Quan hệ': 'Родственная связь', 'Số căn cước': 'Номер удостоверения', 'Ngày sinh': 'Дата рождения', 'Ngày mất': 'Дата смерти', 'Ngày dỗ': 'День поминовения', 'Ví dụ: Con trai trưởng': 'Пример: старший сын', 'Con của': 'Ребёнок', 'Con cái': 'Дети', 'Chưa có thông tin con cái.': 'Нет информации о детях.', 'Hồ sơ thành viên': 'Профиль участника', 'Sửa hồ sơ thành viên': 'Изменить профиль участника', 'Sự kiện gia đình': 'Семейные события', 'Ngày sinh nhật và ngày dỗ được lấy từ thông tin hồ sơ thành viên.': 'Дни рождения и поминальные дни берутся из профилей участников.', 'Sinh nhật': 'День рождения', 'Lặp lại hằng năm': 'Повторяется ежегодно', 'Chưa có sự kiện nào được cập nhật.': 'События ещё не добавлены.', 'Hãy thêm ngày sinh hoặc ngày mất và ngày dỗ trong hồ sơ thành viên.': 'Добавьте дату рождения или дату смерти и день поминовения в профиль участника.' },
  ja: { 'Ảnh đại diện': 'プロフィール写真', 'Đã chọn ảnh': '写真を選択済み', 'Chọn ảnh dưới 240 KB': '240 KB 未満の画像を選択', 'Ảnh đại diện cần là ảnh dưới 240 KB.': 'プロフィール写真は 240 KB 未満の画像にしてください。', 'Quan hệ': '続柄', 'Số căn cước': '身分証番号', 'Ngày sinh': '生年月日', 'Ngày mất': '没年月日', 'Ngày dỗ': '命日', 'Ví dụ: Con trai trưởng': '例：長男', 'Con của': 'の子', 'Con cái': '子ども', 'Chưa có thông tin con cái.': '子どもの情報はありません。', 'Hồ sơ thành viên': 'メンバープロフィール', 'Sửa hồ sơ thành viên': 'メンバープロフィールを編集', 'Sự kiện gia đình': '家族の行事', 'Ngày sinh nhật và ngày dỗ được lấy từ thông tin hồ sơ thành viên.': '誕生日と命日はメンバーのプロフィールから取得されます。', 'Sinh nhật': '誕生日', 'Lặp lại hằng năm': '毎年繰り返し', 'Chưa có sự kiện nào được cập nhật.': 'まだ行事は登録されていません。', 'Hãy thêm ngày sinh hoặc ngày mất và ngày dỗ trong hồ sơ thành viên.': 'メンバーのプロフィールに生年月日、または没年月日と命日を追加してください。' },
  de: { 'Ảnh đại diện': 'Profilbild', 'Đã chọn ảnh': 'Bild ausgewählt', 'Chọn ảnh dưới 240 KB': 'Bild unter 240 KB auswählen', 'Ảnh đại diện cần là ảnh dưới 240 KB.': 'Das Profilbild muss kleiner als 240 KB sein.', 'Quan hệ': 'Verwandtschaft', 'Số căn cước': 'Ausweisnummer', 'Ngày sinh': 'Geburtsdatum', 'Ngày mất': 'Sterbedatum', 'Ngày dỗ': 'Gedenktag', 'Ví dụ: Con trai trưởng': 'Beispiel: ältester Sohn', 'Con của': 'Kind von', 'Con cái': 'Kinder', 'Chưa có thông tin con cái.': 'Noch keine Informationen zu Kindern.', 'Hồ sơ thành viên': 'Mitgliederprofil', 'Sửa hồ sơ thành viên': 'Mitgliederprofil bearbeiten', 'Sự kiện gia đình': 'Familienereignisse', 'Ngày sinh nhật và ngày dỗ được lấy từ thông tin hồ sơ thành viên.': 'Geburtstage und Gedenktage stammen aus den Mitgliederprofilen.', 'Sinh nhật': 'Geburtstag', 'Lặp lại hằng năm': 'Jährlich wiederkehrend', 'Chưa có sự kiện nào được cập nhật.': 'Es wurden noch keine Ereignisse eingetragen.', 'Hãy thêm ngày sinh hoặc ngày mất và ngày dỗ trong hồ sơ thành viên.': 'Fügen Sie dem Mitgliederprofil ein Geburtsdatum oder ein Sterbedatum und einen Gedenktag hinzu.' },
};

export function text(language: Language, vietnamese: string) { return language === 'vi' ? vietnamese : memberExtra[language][vietnamese] ?? profileExtra[language][vietnamese] ?? extra[language][vietnamese] ?? vietnamese; }
