import { NextResponse } from 'next/server';
import { getDatabase } from '@/db';
import { getFamilyDataMode } from '@/lib/family-data-mode';
import { SAMPLE_FIXTURE_VERSION,sampleMaterialItems } from '@/lib/sample-fixtures';
type MaterialItem={id:string;parent_id:string|null;kind:'folder'|'note'|'link';title:string;content:string;created_by_username:string;updated_by_username:string;created_at:number;updated_at:number};const SAMPLE_MARKER_KEY='sample_material_fixture_version';
async function ensureSampleMaterials(){const db=getDatabase();const marker=await db.prepare('SELECT value FROM app_settings WHERE key=?').bind(SAMPLE_MARKER_KEY).first<{value:string}>();if(marker?.value===SAMPLE_FIXTURE_VERSION)return;const statements=sampleMaterialItems.map(item=>db.prepare(`INSERT INTO material_items (id,parent_id,kind,title,content,created_by_username,updated_by_username,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING`).bind(item.id,item.parent_id,item.kind,item.title,item.content,item.created_by_username,item.updated_by_username,item.created_at,item.updated_at));statements.push(db.prepare(`INSERT INTO app_settings (key,value,updated_at,updated_by) VALUES (?,?,?,NULL) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at`).bind(SAMPLE_MARKER_KEY,SAMPLE_FIXTURE_VERSION,Date.now()));await db.batch(statements);}
async function items(sample:boolean){if(sample)await ensureSampleMaterials();const scope=sample?"id LIKE 'sample-%'":"id NOT LIKE 'sample-%'";const result=await getDatabase().prepare(`SELECT id,parent_id,kind,title,content,created_by_username,updated_by_username,created_at,updated_at FROM material_items WHERE ${scope} ORDER BY updated_at DESC,title COLLATE NOCASE ASC`).all<MaterialItem>();return result.results;}
export async function GET(){try{const sampleMode=(await getFamilyDataMode())==='sample';return NextResponse.json({items:await items(sampleMode),sampleMode});}catch{return NextResponse.json({message:'Không thể tải tư liệu lúc này.'},{status:500});}}
function approvalOnly(){return NextResponse.json({message:'Tư liệu được lưu local. Hãy gửi yêu cầu để quản trị viên duyệt trước khi cập nhật dữ liệu chung.'},{status:409});}export async function POST(){return approvalOnly();}export async function PATCH(){return approvalOnly();}export async function DELETE(){return approvalOnly();}
