import { env } from 'cloudflare:workers';
import { NextResponse } from 'next/server';
import { getDatabase } from '@/db';
import { getInternalUser } from '@/app/internal-auth';

async function ensureSchema(){const db=getDatabase();await db.batch([
 db.prepare(`CREATE TABLE IF NOT EXISTS admin_notifications (id TEXT PRIMARY KEY NOT NULL,target_user_id TEXT NOT NULL,target_username TEXT NOT NULL,kind TEXT NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL,request_id TEXT,read_at INTEGER,created_at INTEGER NOT NULL)`),
 db.prepare(`CREATE INDEX IF NOT EXISTS idx_admin_notifications_target_created ON admin_notifications(target_user_id,created_at)`)
]);}
function validEmailList(value:string){const list=value.split(',').map(v=>v.trim()).filter(Boolean);if(!list.length)return false;return list.every(v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v));}

export async function GET(){const user=await getInternalUser();if(!user)return NextResponse.json({message:'Cần đăng nhập.'},{status:401});await ensureSchema();const db=getDatabase();const result=await db.prepare(`SELECT id,kind,title,body,request_id,read_at,created_at FROM admin_notifications WHERE target_user_id=? ORDER BY created_at DESC LIMIT 50`).bind(user.id).all();let email='';if(user.role==='super_admin'){const row=await db.prepare(`SELECT value FROM app_settings WHERE key='admin_notification_email'`).first<{value:string}>();email=row?.value||'';}const runtime=env as unknown as {RESEND_API_KEY?:string};return NextResponse.json({notifications:result.results,email,emailProviderConfigured:Boolean(runtime.RESEND_API_KEY),isAdmin:user.role==='super_admin'});}

export async function PATCH(request:Request){const user=await getInternalUser();if(!user)return NextResponse.json({message:'Cần đăng nhập.'},{status:401});await ensureSchema();const body=await request.json().catch(()=>null) as {id?:string;readAll?:boolean;email?:string}|null;const db=getDatabase();if(typeof body?.email==='string'){if(user.role!=='super_admin')return NextResponse.json({message:'Chỉ quản trị viên được cài email nhận thông báo.'},{status:403});const email=body.email.trim();if(email&&!validEmailList(email))return NextResponse.json({message:'Địa chỉ email không hợp lệ. Có thể nhập nhiều email, cách nhau bằng dấu phẩy.'},{status:400});await db.prepare(`INSERT INTO app_settings (key,value,updated_at,updated_by) VALUES ('admin_notification_email',?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at,updated_by=excluded.updated_by`).bind(email,Date.now(),user.id).run();return NextResponse.json({ok:true,email});}if(body?.readAll){await db.prepare(`UPDATE admin_notifications SET read_at=? WHERE target_user_id=? AND read_at IS NULL`).bind(Date.now(),user.id).run();return NextResponse.json({ok:true});}if(body?.id){await db.prepare(`UPDATE admin_notifications SET read_at=? WHERE id=? AND target_user_id=?`).bind(Date.now(),body.id,user.id).run();return NextResponse.json({ok:true});}return NextResponse.json({message:'Yêu cầu không hợp lệ.'},{status:400});}
