import { env } from 'cloudflare:workers';
import { NextResponse } from 'next/server';
import { getDatabase, writeAuditLog } from '@/db';
import { getInternalUser } from '@/app/internal-auth';

const MAX_PAYLOAD=4_000_000;
const allowedKinds=new Set(['family','event','material']);
type Change={id:string;kind:string;action:'create'|'update'|'delete';label:string;before?:unknown;after?:unknown};
type FamilyAfter={family?:unknown;dataMode?:'sample'|'official'|'empty'};
type EventEnvelope={eventKind?:'family'|'tomb';event?:Record<string,unknown>};
type MaterialEnvelope={item?:Record<string,unknown>};

async function ensureApprovalSchema(){const db=getDatabase();await db.batch([
 db.prepare(`CREATE TABLE IF NOT EXISTS shared_change_requests (id TEXT PRIMARY KEY NOT NULL,requester_id TEXT NOT NULL,requester_username TEXT NOT NULL,device_label TEXT NOT NULL DEFAULT '',summary TEXT NOT NULL,payload TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',reviewer_id TEXT,reviewer_username TEXT,review_note TEXT NOT NULL DEFAULT '',created_at INTEGER NOT NULL,reviewed_at INTEGER)`),
 db.prepare(`CREATE INDEX IF NOT EXISTS idx_shared_change_requests_status_created ON shared_change_requests(status,created_at)`),
 db.prepare(`CREATE TABLE IF NOT EXISTS admin_notifications (id TEXT PRIMARY KEY NOT NULL,target_user_id TEXT NOT NULL,target_username TEXT NOT NULL,kind TEXT NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL,request_id TEXT,read_at INTEGER,created_at INTEGER NOT NULL)`),
 db.prepare(`CREATE INDEX IF NOT EXISTS idx_admin_notifications_target_created ON admin_notifications(target_user_id,created_at)`)
]);}
function validChanges(value:unknown):value is Change[]{return Array.isArray(value)&&value.length>0&&value.length<=500&&value.every((item)=>{if(!item||typeof item!=='object'||Array.isArray(item))return false;const row=item as Partial<Change>;return typeof row.id==='string'&&row.id.length<=160&&typeof row.kind==='string'&&allowedKinds.has(row.kind)&&(row.action==='create'||row.action==='update'||row.action==='delete')&&typeof row.label==='string'&&row.label.length<=200;});}
function eventKey(kind:'family'|'tomb'){return kind==='family'?'family_work_events':'tomb_sweeping_events';}
function actionLabel(action:Change['action']){return action==='create'?'Thêm':action==='delete'?'Xóa':'Sửa';}
function kindLabel(kind:string){return kind==='family'?'Gia phả / thành viên':kind==='event'?'Sự kiện':kind==='material'?'Tư liệu':kind;}
function htmlEscape(value:string){return value.replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));}
async function sendAdminEmail(requester:string,requestId:string,changes:Change[]){const db=getDatabase();const row=await db.prepare(`SELECT value FROM app_settings WHERE key='admin_notification_email'`).first<{value:string}>();const email=row?.value?.trim();const runtime=env as unknown as {RESEND_API_KEY?:string;NOTIFICATION_FROM_EMAIL?:string};if(!email||!runtime.RESEND_API_KEY)return {sent:false,reason:!email?'missing_recipient':'missing_provider'};const lines=changes.map(c=>`${actionLabel(c.action)} ${kindLabel(c.kind)}: ${c.label}`);const html=`<h2>Yêu cầu cập nhật dữ liệu gia phả</h2><p><b>Người gửi:</b> ${htmlEscape(requester)}</p><p><b>Mã yêu cầu:</b> ${htmlEscape(requestId)}</p><p>Dữ liệu chung chưa thay đổi. Cần đăng nhập tài khoản quản trị và duyệt yêu cầu.</p><ul>${changes.map(c=>`<li><b>${htmlEscape(actionLabel(c.action))}</b> ${htmlEscape(kindLabel(c.kind))}: ${htmlEscape(c.label)}</li>`).join('')}</ul>`;const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${runtime.RESEND_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({from:runtime.NOTIFICATION_FROM_EMAIL||'Gia phả <onboarding@resend.dev>',to:email.split(',').map(v=>v.trim()).filter(Boolean),subject:`[Gia phả] Yêu cầu duyệt dữ liệu từ ${requester}`,html,text:[`Yêu cầu duyệt dữ liệu từ ${requester}`,`Mã: ${requestId}`,'',...lines,'','Dữ liệu chung chưa thay đổi cho đến khi quản trị viên duyệt.'].join('\n')})});return {sent:response.ok,reason:response.ok?'sent':`http_${response.status}`};}
async function notifyAdmins(requester:string,requestId:string,summary:string,changes:Change[]){const db=getDatabase();const admins=await db.prepare(`SELECT id,username FROM users WHERE role='super_admin' AND active=1`).all<{id:string;username:string}>();const body=changes.map(c=>`${actionLabel(c.action)} ${kindLabel(c.kind)}: ${c.label}`).join(' · ').slice(0,1800);if(admins.results.length)await db.batch(admins.results.map(a=>db.prepare(`INSERT INTO admin_notifications (id,target_user_id,target_username,kind,title,body,request_id,created_at) VALUES (?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),a.id,a.username,'shared_change_request',`Yêu cầu dữ liệu chung từ ${requester}`,body||summary,requestId,Date.now())));const email=await sendAdminEmail(requester,requestId,changes).catch(()=>({sent:false,reason:'send_error'}));return {accounts:admins.results.length,email};}
async function notifyRequester(userId:string,username:string,requestId:string,decision:'approved'|'rejected'){const db=getDatabase();await db.prepare(`INSERT INTO admin_notifications (id,target_user_id,target_username,kind,title,body,request_id,created_at) VALUES (?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),userId,username,'shared_change_result',decision==='approved'?'Yêu cầu dữ liệu đã được duyệt':'Yêu cầu dữ liệu bị từ chối',decision==='approved'?'Dữ liệu được duyệt đã được áp dụng vào dữ liệu chung.':'Dữ liệu chung không thay đổi.',requestId,Date.now()).run();}
async function applyEvent(db:D1Database,change:Change,userId:string){const after=change.after as EventEnvelope|undefined;const before=change.before as EventEnvelope|undefined;const kind=after?.eventKind??before?.eventKind;const event=after?.event??before?.event;const id=event&&typeof event.id==='string'?event.id:'';if(!kind||!id)throw new Error('Yêu cầu sự kiện thiếu định danh.');const key=eventKey(kind);const row=await db.prepare('SELECT value FROM app_settings WHERE key=?').bind(key).first<{value:string}>();let events:Record<string,unknown>[]=[];try{const parsed=JSON.parse(row?.value||'[]');if(Array.isArray(parsed))events=parsed;}catch{}if(change.action==='delete')events=events.filter((entry)=>entry.id!==id);else{const index=events.findIndex((entry)=>entry.id===id);if(index>=0)events[index]=after!.event!;else events.push(after!.event!);}await db.prepare(`INSERT INTO app_settings (key,value,updated_at,updated_by) VALUES (?,?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at,updated_by=excluded.updated_by`).bind(key,JSON.stringify(events),Date.now(),userId).run();}
async function applyMaterial(db:D1Database,change:Change,username:string){const after=(change.after as MaterialEnvelope|undefined)?.item;const before=(change.before as MaterialEnvelope|undefined)?.item;const item=after??before;const id=item&&typeof item.id==='string'?item.id:'';if(!id)throw new Error('Yêu cầu tư liệu thiếu định danh.');if(change.action==='delete'){await db.prepare('DELETE FROM material_items WHERE id=?').bind(id).run();return;}const parentId=typeof after?.parent_id==='string'?after.parent_id:null;const kind=String(after?.kind||'');const title=after?.title;const content=after?.content;if(!['folder','note','link'].includes(kind)||typeof title!=='string'||typeof content!=='string')throw new Error('Tư liệu chờ duyệt không hợp lệ.');const now=Date.now();await db.prepare(`INSERT INTO material_items (id,parent_id,kind,title,content,created_by_username,updated_by_username,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET parent_id=excluded.parent_id,kind=excluded.kind,title=excluded.title,content=excluded.content,updated_by_username=excluded.updated_by_username,updated_at=excluded.updated_at`).bind(id,parentId,kind,title,content,typeof after?.created_by_username==='string'?after.created_by_username:username,username,typeof after?.created_at==='number'?after.created_at:now,now).run();}
async function applyChange(db:D1Database,change:Change,user:{id:string;username:string}){if(change.kind==='family'){const after=change.after as FamilyAfter|undefined;if(change.action==='delete'||after?.family===null)await db.prepare(`INSERT INTO family_tree (id,data,updated_at,updated_by) VALUES ('primary','null',?,?) ON CONFLICT(id) DO UPDATE SET data='null',updated_at=excluded.updated_at,updated_by=excluded.updated_by`).bind(Date.now(),user.id).run();else if(after?.family)await db.prepare(`INSERT INTO family_tree (id,data,updated_at,updated_by) VALUES ('primary',?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at,updated_by=excluded.updated_by`).bind(JSON.stringify(after.family),Date.now(),user.id).run();if(after?.dataMode)await db.prepare(`INSERT INTO app_settings (key,value,updated_at,updated_by) VALUES ('family_data_mode',?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at,updated_by=excluded.updated_by`).bind(after.dataMode,Date.now(),user.id).run();return;}if(change.kind==='event')return applyEvent(db,change,user.id);if(change.kind==='material')return applyMaterial(db,change,user.username);throw new Error('Loại thay đổi chưa được hỗ trợ.');}

export async function GET(){const user=await getInternalUser();if(!user)return NextResponse.json({message:'Cần đăng nhập.'},{status:401});await ensureApprovalSchema();const db=getDatabase();const query=user.role==='super_admin'?db.prepare(`SELECT id,requester_username,device_label,summary,payload,status,reviewer_username,review_note,created_at,reviewed_at FROM shared_change_requests ORDER BY created_at DESC LIMIT 100`):db.prepare(`SELECT id,requester_username,device_label,summary,payload,status,reviewer_username,review_note,created_at,reviewed_at FROM shared_change_requests WHERE requester_id=? ORDER BY created_at DESC LIMIT 50`).bind(user.id);const result=await query.all();return NextResponse.json({requests:result.results});}
export async function POST(request:Request){const user=await getInternalUser();if(!user)return NextResponse.json({message:'Cần đăng nhập.'},{status:401});await ensureApprovalSchema();const body=await request.json().catch(()=>null) as {changes?:unknown;deviceLabel?:unknown}|null;if(!body||!validChanges(body.changes))return NextResponse.json({message:'Danh sách thay đổi không hợp lệ.'},{status:400});const payload=JSON.stringify(body.changes);if(payload.length>MAX_PAYLOAD)return NextResponse.json({message:'Gói dữ liệu vượt giới hạn.'},{status:413});const counts=body.changes.reduce<Record<string,number>>((acc,item)=>{acc[item.kind]=(acc[item.kind]||0)+1;return acc;},{});const summary=Object.entries(counts).map(([kind,count])=>`${count} ${kindLabel(kind)}`).join(' · ');const id=crypto.randomUUID();const db=getDatabase();await db.prepare(`INSERT INTO shared_change_requests (id,requester_id,requester_username,device_label,summary,payload,status,created_at) VALUES (?,?,?,?,?,?,'pending',?)`).bind(id,user.id,user.username,typeof body.deviceLabel==='string'?body.deviceLabel.slice(0,120):'',summary,payload,Date.now()).run();const notified=await notifyAdmins(user.username,id,summary,body.changes);await writeAuditLog({actorId:user.id,actorUsername:user.username,action:'Gửi duyệt dữ liệu',entity:'Hệ thống',details:`Yêu cầu ${id}: ${summary}`});return NextResponse.json({ok:true,id,status:'pending',summary,notified});}
export async function PATCH(request:Request){const user=await getInternalUser();if(!user||user.role!=='super_admin')return NextResponse.json({message:'Chỉ quản trị viên được duyệt dữ liệu chung.'},{status:403});await ensureApprovalSchema();const body=await request.json().catch(()=>null) as {id?:string;decision?:'approved'|'rejected';note?:string}|null;if(!body?.id||!['approved','rejected'].includes(body.decision||''))return NextResponse.json({message:'Yêu cầu xử lý không hợp lệ.'},{status:400});const db=getDatabase();const row=await db.prepare(`SELECT id,requester_id,requester_username,payload,status FROM shared_change_requests WHERE id=?`).bind(body.id).first<{id:string;requester_id:string;requester_username:string;payload:string;status:string}>();if(!row||row.status!=='pending')return NextResponse.json({message:'Yêu cầu không còn ở trạng thái chờ duyệt.'},{status:409});const changes=JSON.parse(row.payload) as Change[];try{if(body.decision==='approved')for(const change of changes)await applyChange(db,change,{id:user.id,username:user.username});}catch(error){return NextResponse.json({message:error instanceof Error?error.message:'Không thể áp dụng yêu cầu.'},{status:409});}await db.prepare(`UPDATE shared_change_requests SET status=?,reviewer_id=?,reviewer_username=?,review_note=?,reviewed_at=? WHERE id=? AND status='pending'`).bind(body.decision,user.id,user.username,String(body.note||'').slice(0,1000),Date.now(),body.id).run();await notifyRequester(row.requester_id,row.requester_username,body.id,body.decision);await writeAuditLog({actorId:user.id,actorUsername:user.username,action:body.decision==='approved'?'Duyệt dữ liệu':'Từ chối dữ liệu',entity:'Hệ thống',details:`Yêu cầu ${body.id} từ ${row.requester_username}`});return NextResponse.json({ok:true,status:body.decision});}
